-- migrate:up
-- Based on AMK_SCHEMA_PATCHED.sql (SSOT) - Fixed for FK constraints

-- 1. ENUM Types
CREATE TYPE "admin_action_enum" AS ENUM ('create', 'update', 'banned', 'reorder', 'publish', 'unpublish');
CREATE TYPE "user_auth_enum" AS ENUM ('HYMN', 'admin', 'manager', 'learner');
CREATE TYPE "user_language_enum" AS ENUM ('ko', 'en');
CREATE TYPE "user_gender_enum" AS ENUM ('none', 'male', 'female', 'other');
CREATE TYPE "user_action_log_enum" AS ENUM ('signup', 'find_id', 'reset_pw', 'update');
CREATE TYPE "user_set_language_enum" AS ENUM ('ko', 'en');
CREATE TYPE "login_device_enum" AS ENUM ('mobile', 'tablet', 'desktop', 'other');
CREATE TYPE "login_method_enum" AS ENUM ('email', 'google', 'apple');
CREATE TYPE "login_state_enum" AS ENUM ('active', 'revoked', 'expired', 'logged_out');
CREATE TYPE "login_event_enum" AS ENUM ('login', 'logout', 'refresh', 'rotate', 'fail');
CREATE TYPE "video_state_enum" AS ENUM ('ready', 'open', 'close');
CREATE TYPE "video_access_enum" AS ENUM ('public', 'paid', 'private', 'promote');
CREATE TYPE "study_state_enum" AS ENUM ('ready', 'open', 'close');
CREATE TYPE "study_program_enum" AS ENUM ('basic_pronunciation', 'basic_word', 'basic_900', 'topik_read', 'topik_listen', 'topik_write', 'tbc');
CREATE TYPE "study_task_kind_enum" AS ENUM ('choice', 'typing', 'voice');
CREATE TYPE "study_task_log_action_enum" AS ENUM ('view', 'start', 'answer', 'finish', 'explain');
CREATE TYPE "lesson_item_kind_enum" AS ENUM ('video', 'task');

-- 2. Tables
CREATE TABLE "USERS" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_auth" user_auth_enum NOT NULL DEFAULT 'learner',
  "user_state" boolean NOT NULL DEFAULT true,
  "user_email" varchar(255) UNIQUE NOT NULL,
  "user_password" text NOT NULL,
  "user_name" varchar(100) NOT NULL,
  "user_nickname" varchar(100) NOT NULL,
  "user_language" user_language_enum NOT NULL DEFAULT 'ko',
  "user_country" varchar(50) NOT NULL,
  "user_birthday" date NOT NULL,
  "user_gender" user_gender_enum NOT NULL DEFAULT 'none',
  "user_check_email" boolean NOT NULL DEFAULT false,
  "user_terms_service" boolean NOT NULL DEFAULT false,
  "user_terms_personal" boolean NOT NULL DEFAULT false,
  "user_created_at" timestamptz NOT NULL DEFAULT (now()),
  "user_quit_at" timestamptz
);

CREATE TABLE "USERS_LOG" (
  "user_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "updated_by_user_id" bigint,
  "user_action_log" user_action_log_enum NOT NULL,
  "user_action_success" boolean NOT NULL DEFAULT true,
  "user_id" bigint NOT NULL,
  "user_auth_log" user_auth_enum,
  "user_state_log" boolean,
  "user_email_log" varchar(255),
  "user_certify_log" timestamptz,
  "user_password_log" boolean DEFAULT false,
  "user_nickname_log" varchar(100),
  "user_language_log" user_language_enum,
  "user_country_log" varchar(50),
  "user_birthday_log" date,
  "user_gender_log" user_gender_enum,
  "user_terms_service_log" boolean,
  "user_terms_personal_log" boolean,
  "user_log_created_at" timestamptz,
  "user_log_quit_at" timestamptz,
  "user_log_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "USERS_SETTING" (
  "user_id" bigint PRIMARY KEY,
  "user_set_language" user_set_language_enum NOT NULL DEFAULT 'ko',
  "user_set_timezone" varchar(64),
  "user_set_note_email" boolean NOT NULL DEFAULT false,
  "user_set_note_push" boolean NOT NULL DEFAULT false,
  "user_set_created_at" timestamptz NOT NULL DEFAULT (now()),
  "user_set_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "ADMIN_USERS_LOG" (
  "admin_user_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL,
  "admin_pick_user_id" bigint NOT NULL,
  "admin_user_action" admin_action_enum NOT NULL,
  "admin_user_before" jsonb,
  "admin_user_after" jsonb,
  "admin_user_created_at" timestamptz NOT NULL DEFAULT (now()),
  "admin_user_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "USER_EXPORT_DATA" (
  "user_data_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "user_data_status" boolean NOT NULL DEFAULT true,
  "user_data_course" jsonb,
  "user_data_lesson" jsonb,
  "user_data_expires_at" timestamptz,
  "user_data_created_at" timestamptz,
  "user_data_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "LOGIN" (
  "login_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "login_country" char(2) NOT NULL,
  "login_asn" bigint NOT NULL,
  "login_org" varchar(200) NOT NULL,
  "login_ip" inet NOT NULL,
  "login_os" varchar(100),
  "login_browser" varchar(100),
  "login_device" login_device_enum NOT NULL DEFAULT 'other',
  "login_method" login_method_enum NOT NULL DEFAULT 'email',
  "login_session_id" uuid UNIQUE NOT NULL,    -- [수정] UNIQUE 추가
  "login_refresh_hash" varchar(128) UNIQUE,   -- [수정] UNIQUE 추가
  "login_user_agent" text,
  "login_begin_at" timestamptz NOT NULL DEFAULT (now()),
  "login_active_at" timestamptz,
  "login_expire_at" timestamptz,
  "login_state" login_state_enum NOT NULL DEFAULT 'active',
  "login_revoked_reason" text,
  "login_created_at" timestamptz NOT NULL DEFAULT (now()),
  "login_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "LOGIN_LOG" (
  "login_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "login_event_log" login_event_enum,
  "login_success_log" boolean,
  "login_access_log" char(64),
  "login_country_log" char(2),
  "login_asn_log" bigint,
  "login_org_log" varchar(200),
  "login_ip_log" inet,
  "login_os_log" varchar(100),
  "login_browser_log" varchar(100),
  "login_device_log" login_device_enum,
  "login_method_log" login_method_enum,
  "login_session_id_log" uuid,
  "login_refresh_hash_log" varchar(128),
  "login_user_agent_log" text,
  "login_begin_at_log" timestamptz NOT NULL DEFAULT (now()),
  "login_expire_at_log" timestamptz,
  "login_token_id_log" varchar,
  "login_fail_reason_log" text,
  "login_created_at_log" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "REDIS_SESSION" (
  "redis_key" varchar(128) PRIMARY KEY,
  "session_id" uuid UNIQUE NOT NULL,
  "user_id" bigint NOT NULL,
  "login_id" bigint NOT NULL,
  "state" login_state_enum NOT NULL DEFAULT 'active',
  "issued_at" timestamptz NOT NULL DEFAULT (now()),
  "expire_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "ip" inet,
  "user_agent" text,
  "device" login_device_enum,
  "method" login_method_enum,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "REDIS_REFRESH" (
  "redis_key" varchar(160) PRIMARY KEY,
  "refresh_hash" varchar(128) UNIQUE NOT NULL,
  "session_id" uuid NOT NULL,
  "user_id" bigint,
  "issued_at" timestamptz NOT NULL DEFAULT (now()),
  "expire_at" timestamptz NOT NULL,
  "reused_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "REDIS_USER_SESSIONS" (
  "redis_key" varchar(128) PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "session_id" uuid NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT (now()),
  "expire_at" timestamptz NOT NULL
);

CREATE TABLE "VIDEO" (
  "video_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "updated_by_user_id" bigint NOT NULL,
  "video_idx" varchar(100) UNIQUE NOT NULL,
  "video_state" video_state_enum NOT NULL DEFAULT 'ready',
  "video_access" video_access_enum NOT NULL DEFAULT 'public',
  "video_url_vimeo" text NOT NULL,
  "video_created_at" timestamptz NOT NULL DEFAULT (now()),
  "video_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "VIDEO_LOG" (
  "video_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video_id" int NOT NULL,
  "user_id" bigint NOT NULL,
  "login_id" bigint NOT NULL,
  "video_progress_log" int,
  "video_completed_log" boolean NOT NULL DEFAULT false,
  "video_watch_count_log" int NOT NULL DEFAULT 0,
  "video_first_watched_at_log" timestamptz,
  "video_last_watched_at_log" timestamptz,
  "video_last_ip_log" inet,
  "video_last_device_log" login_device_enum,
  "video_last_user_agent_log" jsonb
);

CREATE TABLE "VIDEO_TAG" (
  "video_tag_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video_tag_key" varchar(30) UNIQUE NOT NULL,
  "video_tag_title" varchar(50) NOT NULL,
  "video_tag_subtitle" varchar(100),
  "video_tag_created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "VIDEO_TAG_MAP" (
  "video_id" int NOT NULL,
  "video_tag_id" int NOT NULL
);

CREATE TABLE "VIDEO_STAT_DAILY" (
  "video_stat_date" date,
  "video_id" int NOT NULL,
  "video_stat_views" int NOT NULL DEFAULT 0,
  "video_stat_completes" int NOT NULL DEFAULT 0
);

CREATE TABLE "ADMIN_VIDEO_LOG" (
  "admin_video_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL,
  "admin_pick_video_id" int,
  "admin_pick_video_tag_id" int,
  "admin_video_action" admin_action_enum NOT NULL,
  "admin_video_before" jsonb,
  "admin_video_after" jsonb,
  "admin_video_created_at" timestamptz NOT NULL DEFAULT (now()),
  "admin_video_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "STUDY" (
  "study_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "updated_by_user_id" bigint NOT NULL,
  "study_idx" varchar(100) UNIQUE NOT NULL,
  "study_state" study_state_enum NOT NULL DEFAULT 'ready',
  "study_program" study_program_enum NOT NULL DEFAULT 'tbc',
  "study_title" varchar(80),
  "study_subtitle" varchar(120),
  "study_description" text,
  "study_created_at" timestamptz NOT NULL DEFAULT (now()),
  "study_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "STUDY_TASK" (
  "study_task_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "study_id" int NOT NULL,
  "updated_by_user_id" bigint NOT NULL,
  "study_task_kind" study_task_kind_enum NOT NULL,
  "study_task_seq" int NOT NULL DEFAULT 1,
  "study_task_created_at" timestamptz NOT NULL DEFAULT (now()),
  "study_task_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "STUDY_TASK_CHOICE" (
  "study_task_id" int PRIMARY KEY,
  "study_task_choice_question" text NOT NULL,
  "study_task_choice_1" text NOT NULL,
  "study_task_choice_2" text NOT NULL,
  "study_task_choice_3" text NOT NULL,
  "study_task_choice_4" text NOT NULL,
  "study_task_choice_correct" int NOT NULL,
  "study_task_choice_audio_url" text,
  "study_task_choice_image_url" text
);

CREATE TABLE "STUDY_TASK_TYPING" (
  "study_task_id" int PRIMARY KEY,
  "study_task_typing_question" text,
  "study_task_typing_answer" text,
  "study_task_typing_image_url" text
);

CREATE TABLE "STUDY_TASK_VOICE" (
  "study_task_id" int PRIMARY KEY,
  "study_task_voice_question" text,
  "study_task_voice_answer" text,
  "study_task_voice_audio_url" text,
  "study_task_voice_image_url" text
);

CREATE TABLE "STUDY_EXPLAIN" (
  "study_task_id" int NOT NULL,
  "explain_lang" user_set_language_enum NOT NULL DEFAULT 'ko',
  "explain_title" varchar(120),
  "explain_text" text,
  "explain_media_url" text,
  "explain_created_at" timestamptz NOT NULL DEFAULT (now()),
  "explain_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "STUDY_TASK_STATUS" (
  "study_task_id" int NOT NULL,
  "user_id" bigint NOT NULL,
  "study_task_status_try" int NOT NULL DEFAULT 0,
  "study_task_status_best" int NOT NULL DEFAULT 0,
  "study_task_status_completed" boolean NOT NULL DEFAULT false,
  "study_task_status_last_answer" timestamptz
);

CREATE TABLE "STUDY_TASK_LOG" (
  "study_task_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "study_task_id" int NOT NULL,
  "user_id" bigint NOT NULL,
  "login_id" bigint NOT NULL,
  "study_task_action_log" study_task_log_action_enum NOT NULL,
  "study_task_try_no_log" int NOT NULL DEFAULT 1,
  "study_task_score_log" int DEFAULT 0,
  "study_task_is_correct_log" boolean,
  "study_task_payload_log" jsonb,
  "study_task_created_at_log" timestamptz NOT NULL DEFAULT (now()),
  "study_task_ip_log" inet,
  "study_task_device_log" login_device_enum,
  "study_task_user_agent_log" jsonb
);

CREATE TABLE "ADMIN_STUDY_LOG" (
  "admin_study_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL,
  "admin_pick_study_id" int NOT NULL,
  "admin_pick_task_id" int,
  "admin_study_action" admin_action_enum NOT NULL,
  "admin_study_before" jsonb,
  "admin_study_after" jsonb,
  "admin_study_created_at" timestamptz NOT NULL DEFAULT (now()),
  "admin_study_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "LESSON" (
  "lesson_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "updated_by_user_id" bigint NOT NULL,
  "lesson_idx" varchar(100) UNIQUE NOT NULL,
  "lesson_title" varchar(120) NOT NULL,
  "lesson_subtitle" varchar(200),
  "lesson_description" text,
  "lesson_created_at" timestamptz NOT NULL DEFAULT (now()),
  "lesson_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "LESSON_ITEM" (
  "lesson_id" int NOT NULL,
  "lesson_item_seq" int NOT NULL DEFAULT 1,
  "lesson_item_kind" lesson_item_kind_enum NOT NULL DEFAULT 'video',
  "video_id" int,
  "study_task_id" int
);

CREATE TABLE "LESSON_PROGRESS" (
  "lesson_id" int NOT NULL,
  "user_id" bigint NOT NULL,
  "lesson_progress_percent" int NOT NULL DEFAULT 0,
  "lesson_progress_last_item_seq" int,
  "lesson_progress_last_progress_at" timestamptz
);

CREATE TABLE "ADMIN_LESSON_LOG" (
  "admin_lesson_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL,
  "admin_pick_lesson_id" int NOT NULL,
  "admin_pick_item_seq" int,
  "admin_pick_video_id" int,
  "admin_pick_task_id" int,
  "admin_lesson_action" admin_action_enum NOT NULL,
  "admin_lesson_before" jsonb,
  "admin_lesson_after" jsonb,
  "admin_lesson_created_at" timestamptz NOT NULL DEFAULT (now()),
  "admin_lesson_updated_at" timestamptz NOT NULL DEFAULT (now())
);

-- Foreign Keys
ALTER TABLE "USERS_LOG" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "USERS_SETTING" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "ADMIN_USERS_LOG" ADD FOREIGN KEY ("admin_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "ADMIN_USERS_LOG" ADD FOREIGN KEY ("admin_pick_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "USER_EXPORT_DATA" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "LOGIN" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "LOGIN_LOG" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id") ON DELETE SET NULL;
ALTER TABLE "REDIS_SESSION" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "REDIS_SESSION" ADD FOREIGN KEY ("login_id") REFERENCES "LOGIN" ("login_id");
ALTER TABLE "REDIS_REFRESH" ADD FOREIGN KEY ("session_id") REFERENCES "LOGIN" ("login_session_id");
ALTER TABLE "REDIS_REFRESH" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "REDIS_USER_SESSIONS" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "REDIS_USER_SESSIONS" ADD FOREIGN KEY ("session_id") REFERENCES "LOGIN" ("login_session_id");
ALTER TABLE "REDIS_SESSION" ADD FOREIGN KEY ("session_id") REFERENCES "LOGIN" ("login_session_id");
ALTER TABLE "VIDEO" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "VIDEO_LOG" ADD FOREIGN KEY ("video_id") REFERENCES "VIDEO" ("video_id");
ALTER TABLE "VIDEO_LOG" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "VIDEO_LOG" ADD FOREIGN KEY ("login_id") REFERENCES "LOGIN" ("login_id");
ALTER TABLE "VIDEO_TAG_MAP" ADD FOREIGN KEY ("video_id") REFERENCES "VIDEO" ("video_id");
ALTER TABLE "VIDEO_TAG_MAP" ADD FOREIGN KEY ("video_tag_id") REFERENCES "VIDEO_TAG" ("video_tag_id");
ALTER TABLE "VIDEO_STAT_DAILY" ADD FOREIGN KEY ("video_id") REFERENCES "VIDEO" ("video_id");
ALTER TABLE "ADMIN_VIDEO_LOG" ADD FOREIGN KEY ("admin_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "ADMIN_VIDEO_LOG" ADD FOREIGN KEY ("admin_pick_video_id") REFERENCES "VIDEO" ("video_id");
ALTER TABLE "ADMIN_VIDEO_LOG" ADD FOREIGN KEY ("admin_pick_video_tag_id") REFERENCES "VIDEO_TAG" ("video_tag_id");
ALTER TABLE "STUDY" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "STUDY_TASK" ADD FOREIGN KEY ("study_id") REFERENCES "STUDY" ("study_id");
ALTER TABLE "STUDY_TASK" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "STUDY_TASK_CHOICE" ADD FOREIGN KEY ("study_task_id") REFERENCES "STUDY_TASK" ("study_task_id");
ALTER TABLE "STUDY_TASK_TYPING" ADD FOREIGN KEY ("study_task_id") REFERENCES "STUDY_TASK" ("study_task_id");
ALTER TABLE "STUDY_TASK_VOICE" ADD FOREIGN KEY ("study_task_id") REFERENCES "STUDY_TASK" ("study_task_id");
ALTER TABLE "STUDY_EXPLAIN" ADD FOREIGN KEY ("study_task_id") REFERENCES "STUDY_TASK" ("study_task_id");
ALTER TABLE "STUDY_TASK_STATUS" ADD FOREIGN KEY ("study_task_id") REFERENCES "STUDY_TASK" ("study_task_id");
ALTER TABLE "STUDY_TASK_STATUS" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "STUDY_TASK_LOG" ADD FOREIGN KEY ("study_task_id") REFERENCES "STUDY_TASK" ("study_task_id");
ALTER TABLE "STUDY_TASK_LOG" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "STUDY_TASK_LOG" ADD FOREIGN KEY ("login_id") REFERENCES "LOGIN" ("login_id");
ALTER TABLE "ADMIN_STUDY_LOG" ADD FOREIGN KEY ("admin_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "ADMIN_STUDY_LOG" ADD FOREIGN KEY ("admin_pick_study_id") REFERENCES "STUDY" ("study_id");
ALTER TABLE "ADMIN_STUDY_LOG" ADD FOREIGN KEY ("admin_pick_task_id") REFERENCES "STUDY_TASK" ("study_task_id");
ALTER TABLE "LESSON" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "LESSON_ITEM" ADD FOREIGN KEY ("lesson_id") REFERENCES "LESSON" ("lesson_id");
ALTER TABLE "LESSON_ITEM" ADD FOREIGN KEY ("video_id") REFERENCES "VIDEO" ("video_id");
ALTER TABLE "LESSON_ITEM" ADD FOREIGN KEY ("study_task_id") REFERENCES "STUDY_TASK" ("study_task_id");
ALTER TABLE "LESSON_PROGRESS" ADD FOREIGN KEY ("lesson_id") REFERENCES "LESSON" ("lesson_id");
ALTER TABLE "LESSON_PROGRESS" ADD FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "ADMIN_LESSON_LOG" ADD FOREIGN KEY ("admin_user_id") REFERENCES "USERS" ("user_id");
ALTER TABLE "ADMIN_LESSON_LOG" ADD FOREIGN KEY ("admin_pick_lesson_id") REFERENCES "LESSON" ("lesson_id");
ALTER TABLE "ADMIN_LESSON_LOG" ADD FOREIGN KEY ("admin_pick_video_id") REFERENCES "VIDEO" ("video_id");
ALTER TABLE "ADMIN_LESSON_LOG" ADD FOREIGN KEY ("admin_pick_task_id") REFERENCES "STUDY_TASK" ("study_task_id");

-- Indexes (Explicit indexes still good for performance, but Unique constraints handle uniqueness)
CREATE INDEX "index_admin_user_id" ON "ADMIN_USERS_LOG" ("admin_user_id");
CREATE INDEX "index_target_user_id" ON "ADMIN_USERS_LOG" ("admin_pick_user_id");
CREATE INDEX "index_export_data_user_id" ON "USER_EXPORT_DATA" ("user_id");
CREATE INDEX "index_login_user_id" ON "LOGIN" ("user_id");
CREATE INDEX "index_login_state" ON "LOGIN" ("login_state");
CREATE INDEX "index_login_begin_at" ON "LOGIN" ("login_begin_at");
CREATE INDEX "index_login_expire_at" ON "LOGIN" ("login_expire_at");
CREATE INDEX "index_login_active_by_user" ON "LOGIN" ("user_id", "login_state");
CREATE INDEX "index_login_user_id_login_begin_at_log" ON "LOGIN_LOG" ("user_id", "login_begin_at_log");
CREATE INDEX "index_login_event_log" ON "LOGIN_LOG" ("login_event_log");
CREATE INDEX "index_redis_refresh_session_id" ON "REDIS_REFRESH" ("session_id");
CREATE INDEX "index_redis_refresh_user_id" ON "REDIS_REFRESH" ("user_id");
CREATE INDEX "index_redis_user_sessions_user_id" ON "REDIS_USER_SESSIONS" ("user_id");
CREATE UNIQUE INDEX "unique_redis_user_sessions_session_id" ON "REDIS_USER_SESSIONS" ("session_id");
CREATE INDEX "index_video_state_video_access" ON "VIDEO" ("video_state", "video_access");
CREATE INDEX "index_video_created_at" ON "VIDEO" ("video_created_at");
CREATE UNIQUE INDEX "unique_video_id_user_id" ON "VIDEO_LOG" ("video_id", "user_id");
CREATE INDEX "index_user_id_video_last_watched_at_log" ON "VIDEO_LOG" ("user_id", "video_last_watched_at_log");
CREATE INDEX "index_video_id_video_last_watched_at_log" ON "VIDEO_LOG" ("video_id", "video_last_watched_at_log");
CREATE UNIQUE INDEX "unique_video_id_video_tag_id" ON "VIDEO_TAG_MAP" ("video_id", "video_tag_id");
CREATE UNIQUE INDEX "unique_video_stat_date_video_id" ON "VIDEO_STAT_DAILY" ("video_stat_date", "video_id");
CREATE INDEX "index_admin_user_id_video" ON "ADMIN_VIDEO_LOG" ("admin_user_id");
CREATE INDEX "index_admin_pick_video_id" ON "ADMIN_VIDEO_LOG" ("admin_pick_video_id");
CREATE UNIQUE INDEX "unique_study_id_study_task_seq" ON "STUDY_TASK" ("study_id", "study_task_seq");
CREATE INDEX "index_study_task_kind" ON "STUDY_TASK" ("study_task_kind");
CREATE UNIQUE INDEX "unique_study_task_explain_lang" ON "STUDY_EXPLAIN" ("study_task_id", "explain_lang");
CREATE INDEX "index_explain_lang" ON "STUDY_EXPLAIN" ("explain_lang");
CREATE UNIQUE INDEX "unique_study_task_id_user_id" ON "STUDY_TASK_STATUS" ("study_task_id", "user_id");
CREATE INDEX "index_user_id_study_task_status_last_answer" ON "STUDY_TASK_STATUS" ("user_id", "study_task_status_last_answer");
CREATE INDEX "index_tasklog_user_task_time" ON "STUDY_TASK_LOG" ("user_id", "study_task_id", "study_task_created_at_log");
CREATE INDEX "index_tasklog_task_attempt" ON "STUDY_TASK_LOG" ("study_task_id", "study_task_try_no_log");
CREATE INDEX "index_tasklog_login_time" ON "STUDY_TASK_LOG" ("login_id", "study_task_created_at_log");
CREATE INDEX "index_admin_study_actor" ON "ADMIN_STUDY_LOG" ("admin_user_id");
CREATE INDEX "index_admin_study_target" ON "ADMIN_STUDY_LOG" ("admin_pick_study_id");
CREATE INDEX "index_admin_study_task_target" ON "ADMIN_STUDY_LOG" ("admin_pick_task_id");
CREATE UNIQUE INDEX "unique_lesson_id_lesson_item_seq" ON "LESSON_ITEM" ("lesson_id", "lesson_item_seq");
CREATE INDEX "index_video_id" ON "LESSON_ITEM" ("video_id");
CREATE INDEX "index_study_task_id" ON "LESSON_ITEM" ("study_task_id");
CREATE UNIQUE INDEX "unique_lesson_id_user_id" ON "LESSON_PROGRESS" ("lesson_id", "user_id");
CREATE INDEX "index_user_id" ON "LESSON_PROGRESS" ("user_id");
CREATE INDEX "index_admin_lesson_actor" ON "ADMIN_LESSON_LOG" ("admin_user_id");
CREATE INDEX "index_admin_lesson_target" ON "ADMIN_LESSON_LOG" ("admin_pick_lesson_id");
CREATE INDEX "index_admin_lesson_item_seq" ON "ADMIN_LESSON_LOG" ("admin_pick_item_seq");
CREATE INDEX "index_admin_lesson_video_target" ON "ADMIN_LESSON_LOG" ("admin_pick_video_id");
CREATE INDEX "index_admin_lesson_task_target" ON "ADMIN_LESSON_LOG" ("admin_pick_task_id");

-- migrate:down
DROP TABLE IF EXISTS "ADMIN_LESSON_LOG";
DROP TABLE IF EXISTS "LESSON_PROGRESS";
DROP TABLE IF EXISTS "LESSON_ITEM";
DROP TABLE IF EXISTS "LESSON";
DROP TABLE IF EXISTS "ADMIN_STUDY_LOG";
DROP TABLE IF EXISTS "STUDY_TASK_LOG";
DROP TABLE IF EXISTS "STUDY_TASK_STATUS";
DROP TABLE IF EXISTS "STUDY_EXPLAIN";
DROP TABLE IF EXISTS "STUDY_TASK_VOICE";
DROP TABLE IF EXISTS "STUDY_TASK_TYPING";
DROP TABLE IF EXISTS "STUDY_TASK_CHOICE";
DROP TABLE IF EXISTS "STUDY_TASK";
DROP TABLE IF EXISTS "STUDY";
DROP TABLE IF EXISTS "ADMIN_VIDEO_LOG";
DROP TABLE IF EXISTS "VIDEO_STAT_DAILY";
DROP TABLE IF EXISTS "VIDEO_TAG_MAP";
DROP TABLE IF EXISTS "VIDEO_TAG";
DROP TABLE IF EXISTS "VIDEO_LOG";
DROP TABLE IF EXISTS "VIDEO";
DROP TABLE IF EXISTS "REDIS_USER_SESSIONS";
DROP TABLE IF EXISTS "REDIS_REFRESH";
DROP TABLE IF EXISTS "REDIS_SESSION";
DROP TABLE IF EXISTS "LOGIN_LOG";
DROP TABLE IF EXISTS "LOGIN";
DROP TABLE IF EXISTS "USER_EXPORT_DATA";
DROP TABLE IF EXISTS "ADMIN_USERS_LOG";
DROP TABLE IF EXISTS "USERS_SETTING";
DROP TABLE IF EXISTS "USERS_LOG";
DROP TABLE IF EXISTS "USERS";

DROP TYPE IF EXISTS "lesson_item_kind_enum";
DROP TYPE IF EXISTS "study_task_log_action_enum";
DROP TYPE IF EXISTS "study_task_kind_enum";
DROP TYPE IF EXISTS "study_program_enum";
DROP TYPE IF EXISTS "study_state_enum";
DROP TYPE IF EXISTS "video_access_enum";
DROP TYPE IF EXISTS "video_state_enum";
DROP TYPE IF EXISTS "login_event_enum";
DROP TYPE IF EXISTS "login_state_enum";
DROP TYPE IF EXISTS "login_method_enum";
DROP TYPE IF EXISTS "login_device_enum";
DROP TYPE IF EXISTS "user_set_language_enum";
DROP TYPE IF EXISTS "user_action_log_enum";
DROP TYPE IF EXISTS "user_gender_enum";
DROP TYPE IF EXISTS "user_language_enum";
DROP TYPE IF EXISTS "user_auth_enum";
DROP TYPE IF EXISTS "admin_action_enum";