--! up
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'login_device_enum') THEN
    CREATE TYPE login_device_enum AS ENUM ('mobile','tablet','desktop','other');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'login_method_enum') THEN
    CREATE TYPE login_method_enum AS ENUM ('email','google','apple');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'login_event_enum') THEN
    CREATE TYPE login_event_enum AS ENUM ('login','logout','refresh','rotate','fail');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'login_state_enum') THEN
    CREATE TYPE login_state_enum AS ENUM ('active','revoked','expired','logged_out');
  END IF;
END $$;

-- 현재/과거 세션 상태
CREATE TABLE IF NOT EXISTS public.login (
  login_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  login_success   BOOLEAN NOT NULL DEFAULT TRUE,
  login_ip        INET,
  login_device    login_device_enum NOT NULL DEFAULT 'other',
  login_browser   VARCHAR(100),
  login_os        VARCHAR(100),
  login_method    login_method_enum NOT NULL DEFAULT 'email',
  -- 세션·리프레시 스킴 (Redis와 1:1/느슨 연결)
  session_id      UUID NOT NULL,        -- Redis: ak:session:<sid> 의 <sid>
  refresh_hash    VARCHAR(128),         -- Redis: ak:refresh:<hash> 의 <hash>(평문 토큰은 쿠키에만)

  user_agent      TEXT,

  login_time_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at    TIMESTAMPTZ,
  logout_time_at  TIMESTAMPTZ,

  state           login_state_enum NOT NULL DEFAULT 'active',
  revoked_reason  TEXT,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT chk_logout_after_login
    CHECK (logout_time_at IS NULL OR logout_time_at >= login_time_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_login_session_id ON public.login(session_id);
CREATE INDEX IF NOT EXISTS idx_login_user_id     ON public.login(user_id);
CREATE INDEX IF NOT EXISTS idx_login_state       ON public.login(state);
CREATE INDEX IF NOT EXISTS idx_login_time        ON public.login(login_time_at DESC);

-- 같은 refresh_hash의 동시 활성세션 방지(선택·권장)
CREATE UNIQUE INDEX IF NOT EXISTS uq_login_refresh_active
  ON public.login(refresh_hash)
  WHERE refresh_hash IS NOT NULL AND state = 'active';

CREATE OR REPLACE FUNCTION public._touch_login_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_login_touch ON public.login;
CREATE TRIGGER trg_login_touch
BEFORE UPDATE ON public.login
FOR EACH ROW EXECUTE FUNCTION public._touch_login_updated_at();

-- 인증 이벤트 로그(append-only)
CREATE TABLE IF NOT EXISTS public.login_log (
  login_log_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL,

  event               login_event_enum NOT NULL,  -- login/logout/refresh/rotate/fail
  login_success_log   BOOLEAN NOT NULL,

  login_ip_log        INET,
  login_device_log    VARCHAR(20),
  login_browser_log   VARCHAR(100),
  login_os_log        VARCHAR(100),
  login_method_log    VARCHAR(20),

  session_id          UUID,               -- 성공/갱신/로그아웃 등에 해당 세션 아이디 남김
  refresh_hash        VARCHAR(128),

  user_agent_log      TEXT,

  login_log_time_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  logout_log_time_at  TIMESTAMPTZ,
  login_log_token_id  VARCHAR,            -- 필요 시 외부 게이트웨이 토큰 id 기록
  login_log_fail_reason TEXT,

  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_login_log_user_time ON public.login_log(user_id, login_log_time_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_log_event     ON public.login_log(event);

--! down
DROP TABLE IF EXISTS public.login_log;
DROP TRIGGER IF EXISTS trg_login_touch ON public.login;
DROP FUNCTION IF EXISTS public._touch_login_updated_at();
DROP TABLE IF EXISTS public.login;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'login_device_enum') THEN
    DROP TYPE login_device_enum;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'login_method_enum') THEN
    DROP TYPE login_method_enum;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'login_event_enum') THEN
    DROP TYPE login_event_enum;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'login_state_enum') THEN
    DROP TYPE login_state_enum;
  END IF;
END $$;
