-- migrate:up
-- dbdiagram.io ERD 기반 초기 스키마 (IDENTITY: START WITH 1, INCREMENT BY 1)

-- 1) ENUM 타입
CREATE TYPE user_auth_enum   AS ENUM ('HYMN', 'admin', 'manager', 'learner');
CREATE TYPE user_state_enum  AS ENUM ('on', 'off');
CREATE TYPE user_gender_enum AS ENUM ('none', 'male', 'female', 'other');

-- 2) USERS
CREATE TABLE public.users (
  user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  user_auth           user_auth_enum  NOT NULL DEFAULT 'learner',
  user_state          user_state_enum NOT NULL DEFAULT 'on',
  user_email          VARCHAR(255) UNIQUE,
  user_password       TEXT,
  user_name           VARCHAR(100),
  user_nickname       VARCHAR(100),
  user_language       VARCHAR(50),
  user_country        VARCHAR(50),
  user_birthday       DATE,
  user_gender         user_gender_enum NOT NULL DEFAULT 'none',
  user_terms_service  BOOLEAN NOT NULL DEFAULT FALSE,
  user_terms_personal BOOLEAN NOT NULL DEFAULT FALSE,
  user_created_at     TIMESTAMP,
  user_quit_at        TIMESTAMP
);

-- 3) USERS_LOG
--  FK 타입은 USERS.user_id(BIGINT)와 일치시키기 위해 BIGINT 사용
CREATE TABLE public.users_log (
  user_log_id              INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  updated_by_user_id       BIGINT REFERENCES public.users(user_id),
  user_id                  BIGINT NOT NULL REFERENCES public.users(user_id),
  user_auth_log            VARCHAR(20),
  user_state_log           VARCHAR(10),
  user_email_log           VARCHAR(255),
  user_password_log        TEXT,
  user_nickname_log        VARCHAR(100),
  user_language_log        VARCHAR(50),
  user_country_log         VARCHAR(50),
  user_birthday_log        DATE,
  user_gender_log          VARCHAR(10),
  user_terms_service_log   BOOLEAN,
  user_terms_personal_log  BOOLEAN,
  user_log_created_at      TIMESTAMP,
  user_log_quit_at         TIMESTAMP,
  user_log_updated_at      TIMESTAMP
);

-- 4) USERS_SETTING
CREATE TABLE public.users_setting (
  user_id              BIGINT PRIMARY KEY REFERENCES public.users(user_id) ON DELETE CASCADE,
  ui_language          VARCHAR(8)  NOT NULL DEFAULT 'en',
  timezone             VARCHAR(64),
  notifications_email  BOOLEAN     NOT NULL DEFAULT TRUE,
  notifications_push   BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at           TIMESTAMP   NOT NULL DEFAULT now(),
  updated_at           TIMESTAMP   NOT NULL DEFAULT now()
);

-- 5) USERS_LANGUAGE_PREF
CREATE TABLE public.users_language_pref (
  user_id     BIGINT      NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  lang_code   VARCHAR(8)  NOT NULL,  -- e.g. en, ko, ne, si, id, vi, th
  priority    INT         NOT NULL,
  is_primary  BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMP   NOT NULL DEFAULT now(),
  updated_at  TIMESTAMP   NOT NULL DEFAULT now(),
  CONSTRAINT pk_users_language_pref PRIMARY KEY (user_id, priority)
);
CREATE UNIQUE INDEX ux_user_language_pref_user_lang ON public.users_language_pref (user_id, lang_code);
CREATE INDEX idx_ulpref_user_priority ON public.users_language_pref (user_id, priority);
CREATE INDEX idx_ulpref_user_primary ON public.users_language_pref (user_id) WHERE is_primary;

-- 6) ADMIN_USERS_ACTION_LOG
CREATE TABLE public.admin_users_action_log (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  actor_user_id  BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE RESTRICT,
  target_user_id BIGINT NOT NULL REFERENCES public.users(user_id),
  action         VARCHAR(32) NOT NULL,  -- e.g. admin_update, admin_block
  before         JSONB,
  after          JSONB,
  created_at     TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_admin_action_target ON public.admin_users_action_log (target_user_id);
CREATE INDEX idx_admin_action_actor  ON public.admin_users_action_log (actor_user_id);

-- 7) USER_EXPORT_JOB
CREATE TABLE public.user_export_job (
  job_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  status     VARCHAR(16) NOT NULL DEFAULT 'queued', -- queued|processing|done|failed
  signed_url TEXT,
  expires_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_export_user_status ON public.user_export_job (user_id, status);
CREATE UNIQUE INDEX ux_export_user_queued ON public.user_export_job (user_id) WHERE status = 'queued';

-- migrate:down
DROP TABLE IF EXISTS public.user_export_job;
DROP TABLE IF EXISTS public.admin_users_action_log;
DROP TABLE IF EXISTS public.users_language_pref;
DROP TABLE IF EXISTS public.users_setting;
DROP TABLE IF EXISTS public.users_log;
DROP TABLE IF EXISTS public.users;
DROP TYPE IF EXISTS user_gender_enum;
DROP TYPE IF EXISTS user_state_enum;
DROP TYPE IF EXISTS user_auth_enum;