-- Payment System Migration (2026-02-15)
-- Paddle 결제 시스템을 위한 ENUM 타입 및 테이블 생성

-- =============================================================================
-- 1. New ENUM Types
-- =============================================================================

CREATE TYPE payment_provider_enum AS ENUM ('paddle');

CREATE TYPE subscription_status_enum AS ENUM (
    'trialing',       -- 무료 체험 중
    'active',         -- 활성 구독
    'past_due',       -- 결제 실패 (유예 기간)
    'paused',         -- 일시정지
    'canceled'        -- 취소됨
);

CREATE TYPE transaction_status_enum AS ENUM (
    'completed',           -- 결제 완료
    'refunded',            -- 전액 환불
    'partially_refunded'   -- 부분 환불
);

CREATE TYPE billing_interval_enum AS ENUM (
    'month_1',    -- 1개월 ($10)
    'month_3',    -- 3개월 ($25)
    'month_6',    -- 6개월 ($50)
    'month_12'    -- 12개월 ($100)
);

-- =============================================================================
-- 2. subscriptions : 구독 정보 (Source of Truth)
-- =============================================================================
CREATE TABLE subscriptions (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    payment_provider payment_provider_enum NOT NULL DEFAULT 'paddle',
    provider_subscription_id VARCHAR(255) NOT NULL,   -- Paddle: sub_xxx
    provider_customer_id VARCHAR(255),                 -- Paddle: ctm_xxx
    status subscription_status_enum NOT NULL DEFAULT 'trialing',
    billing_interval billing_interval_enum NOT NULL,
    current_price_cents INT NOT NULL,                  -- 가격 (센트 단위, 예: 1000 = $10.00)
    trial_started_at TIMESTAMPTZ,
    trial_ends_at TIMESTAMPTZ,
    current_period_start TIMESTAMPTZ,
    current_period_end TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,
    paused_at TIMESTAMPTZ,
    provider_data JSONB,                               -- Provider별 추가 데이터
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 3. transactions : 결제 트랜잭션 기록
-- =============================================================================
CREATE TABLE transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT REFERENCES subscriptions(subscription_id),
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    payment_provider payment_provider_enum NOT NULL DEFAULT 'paddle',
    provider_transaction_id VARCHAR(255) NOT NULL,     -- Paddle: txn_xxx
    status transaction_status_enum NOT NULL,
    amount_cents INT NOT NULL,                          -- 결제 금액 (센트)
    tax_cents INT NOT NULL DEFAULT 0,                   -- 세금 (센트)
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    billing_interval billing_interval_enum,
    provider_data JSONB,
    occurred_at TIMESTAMPTZ NOT NULL,                   -- Provider 측 발생 시간
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 4. webhook_events : 웹훅 이벤트 추적 (멱등성 보장)
-- =============================================================================
CREATE TABLE webhook_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_provider payment_provider_enum NOT NULL DEFAULT 'paddle',
    provider_event_id VARCHAR(255) NOT NULL,            -- Paddle 이벤트 ID (중복 방지)
    event_type VARCHAR(100) NOT NULL,                   -- 이벤트 타입 (예: subscription.activated)
    payload JSONB NOT NULL,                             -- 원본 페이로드
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_provider_event UNIQUE (payment_provider, provider_event_id)
);

-- =============================================================================
-- 5. Indexes
-- =============================================================================

-- subscriptions
CREATE INDEX idx_subscriptions_user_id ON subscriptions (user_id);
CREATE INDEX idx_subscriptions_status ON subscriptions (status);
CREATE UNIQUE INDEX unique_provider_subscription ON subscriptions (payment_provider, provider_subscription_id);

-- transactions
CREATE INDEX idx_transactions_user_id ON transactions (user_id);
CREATE INDEX idx_transactions_subscription_id ON transactions (subscription_id);
CREATE INDEX idx_transactions_provider_txn_id ON transactions (provider_transaction_id);

-- webhook_events
CREATE INDEX idx_webhook_events_type ON webhook_events (event_type);
