-- =============================================================================
-- guide 도메인 — 온라인 콘텐츠(해설집) 테이블 5종 + enum 6종
-- =============================================================================
-- 설계 SoT = docs/AMK_GUIDE_CONTENT_DESIGN.md (사용자 결정 D-0~D-8, 2026-06-12).
-- 원리: "모든 것은 블록"(.txt 세그먼트 스트림 = guide_block 단일 스트림,
--   block_seq 하나로 페이지 순서 완결) + 문장(500)만 학습항목으로 승격.
-- DB = 편집 가능한 SoT (D-0): 초기 시딩 후 admin 편집이 정본.
--   source_version 으로 편집 후 번역 stale 자동 판정.
-- =============================================================================

CREATE TYPE guide_state_enum    AS ENUM ('ready', 'open', 'close');
CREATE TYPE guide_category_enum AS ENUM ('sentence_structure', 'predicate', 'adverbial', 'misc');
-- 교재 10색 테마 (books scripts/textbook/css/themes.css — D-8)
CREATE TYPE guide_theme_enum    AS ENUM ('blue', 'green', 'orange', 'purple', 'pink',
                                         'teal', 'indigo', 'rose', 'amber', 'slate');
-- 해설집 세그먼트 타입 승계 (AMK_CONTENT_SEGMENT_SPEC §2 12종 + 실측 추가 list_item)
CREATE TYPE guide_block_type_enum AS ENUM (
  'title', 'paragraph', 'pattern', 'section', 'vocab', 'ui', 'note',
  'blockquote', 'other', 'table_header', 'table_cell', 'practice', 'list_item');
CREATE TYPE guide_activity_enum   AS ENUM ('sentence_write', 'read_along', 'flashcard',
                                           'matching', 'writing_test');
CREATE TYPE guide_log_action_enum AS ENUM ('view', 'attempt', 'correct', 'wrong',
                                           'reveal', 'complete');

-- 단원 (67행)
CREATE TABLE guide (
  guide_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guide_idx            VARCHAR(100) UNIQUE NOT NULL,   -- 'guidev2-05' ~ 'guidev2-71' (안정 외부키)
  guide_seq            INT NOT NULL,                   -- 표시 순서
  guide_state          guide_state_enum NOT NULL DEFAULT 'ready',  -- ready=숨김 (study 선례)
  guide_category       guide_category_enum NOT NULL,
  guide_theme          guide_theme_enum NOT NULL DEFAULT 'blue',   -- 교재 챕터 테마 승계 (시딩 시 sentences.json 유도)
  guide_source         VARCHAR(50) NOT NULL DEFAULT 'guide500',    -- 미래 콘텐츠군(한글 트랙 등) 수용
  sentence_start       INT,
  sentence_end         INT,
  -- title/subtitle = TITLE/PARAGRAPH 블록의 비정규화 사본 (목록 표시용,
  --   admin 블록 편집 시 동기화 책임 = service 레이어)
  title_ko VARCHAR(200),  title_en VARCHAR(200),
  subtitle_ko VARCHAR(300), subtitle_en VARCHAR(300),
  guide_source_version INT NOT NULL DEFAULT 1,
  updated_by_user_id   BIGINT,
  guide_created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  guide_updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 콘텐츠 블록 (세그먼트 전체 — 번역 대상 + ko학습칸/기호/빈칸 포함, ~14k행)
CREATE TABLE guide_block (
  guide_block_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guide_id             BIGINT NOT NULL REFERENCES guide(guide_id) ON DELETE CASCADE,
  block_seq            INT NOT NULL,                  -- 단원 내 표시 순서 (.txt MMM × 10, 편집 삽입 여유)
  block_type           guide_block_type_enum NOT NULL,
  sentence_no          INT,                           -- 문장 귀속 논리 키 (1~500, NULL=단원 레벨, FK 아님 — explanation_unit.sentence_num 선례)
  text_ko              TEXT,
  text_en              TEXT,                          -- 36언어 번역 원천 (수정 시 source_version+1)
  marker               VARCHAR(40),                   -- symbol_only / table_content_ko_learning / content_ko_learning / table_content_en / empty:짝 / empty:헤더
  table_no INT, row_no INT, col_no INT,               -- 표 좌표 Tn_Rr_Cc (col_no = 행 내 등장 순번, 시각 열 아님)
  col_span INT, row_span INT,                         -- 병합 메타 (NULL=1, 해설집 HTML 1회 추출)
  meta                 JSONB,                         -- 렌더 힌트·확장 예비
  source_version       INT NOT NULL DEFAULT 1,        -- admin 편집(text_ko/text_en 변경) 시 +1
  legacy_key           VARCHAR(50) UNIQUE,            -- 'guidev2:05_001' (초기 시딩분만, 신규 편집 블록 NULL)
  updated_by_user_id   BIGINT,
  guide_block_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  guide_block_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (guide_id, block_seq)
);
CREATE INDEX idx_guide_block_guide_sentence ON guide_block (guide_id, sentence_no);

-- 문장 = 학습항목 오버레이 (500행, 텍스트는 section 블록 1곳 보유 — 중복 0)
CREATE TABLE guide_sentence (
  guide_sentence_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guide_id             BIGINT NOT NULL REFERENCES guide(guide_id) ON DELETE CASCADE,
  sentence_no          INT UNIQUE NOT NULL,           -- 1~500 전역
  guide_block_id       BIGINT UNIQUE NOT NULL REFERENCES guide_block(guide_block_id),  -- = section 블록 (텍스트 SoT)
  pron_ko              TEXT,                          -- 발음형 (후속 rule-based G2P 백필)
  speech_level         VARCHAR(30),                   -- 화계 (값 체계 확정 전 — 주체높임과 2축 분리 원칙, §7.7)
  subject_honorific    BOOLEAN,
  audio_url            TEXT,                          -- 후속 TTS 자산 (D-6)
  updated_by_user_id   BIGINT,
  guide_sentence_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  guide_sentence_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_guide_sentence_guide ON guide_sentence (guide_id);

-- 학습 행위 로그 (STUDY_TASK_LOG 패턴, §3.2.1 log 컬럼 규칙)
CREATE TABLE guide_sentence_log (
  guide_sentence_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guide_sentence_id    BIGINT NOT NULL REFERENCES guide_sentence(guide_sentence_id) ON DELETE CASCADE,
  user_id              BIGINT NOT NULL,
  login_id             BIGINT NOT NULL,               -- 세션 귀속 (session_id 필수화 정책)
  guide_sentence_activity_log guide_activity_enum NOT NULL,
  guide_sentence_action_log   guide_log_action_enum NOT NULL,
  guide_sentence_answer_log   JSONB,                  -- 제출 답안 (향후 점수화·FSRS 데이터 기반)
  guide_sentence_created_at_log TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_guide_sentence_log_user ON guide_sentence_log (user_id, guide_sentence_id);
-- FK 단독 인덱스: 삭제 전파/조인 시 풀스캔 방지 (PK·복합 인덱스는 user_id 선행이라 미적용)
CREATE INDEX idx_guide_sentence_log_sentence ON guide_sentence_log (guide_sentence_id);

-- 학습 상태 요약 (STUDY_TASK_STATUS 패턴)
CREATE TABLE guide_sentence_status (
  guide_sentence_id    BIGINT NOT NULL REFERENCES guide_sentence(guide_sentence_id) ON DELETE CASCADE,
  user_id              BIGINT NOT NULL,
  guide_sentence_status_try_count INT NOT NULL DEFAULT 0,
  guide_sentence_status_is_solved BOOLEAN NOT NULL DEFAULT false,
  guide_sentence_status_last_attempt_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, guide_sentence_id)
);
CREATE INDEX idx_guide_sentence_status_sentence ON guide_sentence_status (guide_sentence_id);

-- 번역 원문 버전 추적: content_translations.source_version < guide_block.source_version → stale
ALTER TABLE content_translations ADD COLUMN source_version INT;  -- 기존 행 NULL = 구 체계
