-- =============================================================================
-- 한글 자판 연습 — 자유 연습 시드 콘텐츠 (writing_practice_seed)
-- =============================================================================
-- study_task 수강 흐름과 독립된 자유 연습용 드릴 컨텐츠.
-- 레벨/유형별로 seq 순서대로 제공된다.
-- =============================================================================

CREATE TABLE writing_practice_seed (
    writing_practice_seed_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    writing_level            writing_level_enum NOT NULL,
    writing_practice_type    writing_practice_type_enum NOT NULL,
    seq                      INT NOT NULL,
    prompt                   TEXT NOT NULL,
    answer                   TEXT NOT NULL,
    hint                     TEXT,
    CONSTRAINT uniq_writing_practice_seed_level_type_seq
        UNIQUE (writing_level, writing_practice_type, seq)
);

CREATE INDEX idx_writing_practice_seed_level_type
    ON writing_practice_seed (writing_level, writing_practice_type, seq);

-- =============================================================================
-- Beginner — jamo (40)
-- 기본 자음 14 + 기본 모음 10 + 쌍자음 5 + 이중모음 11
-- =============================================================================
INSERT INTO writing_practice_seed (writing_level, writing_practice_type, seq, prompt, answer, hint) VALUES
('beginner', 'jamo', 1,  'ㄱ', 'ㄱ', 'giyeok'),
('beginner', 'jamo', 2,  'ㄴ', 'ㄴ', 'nieun'),
('beginner', 'jamo', 3,  'ㄷ', 'ㄷ', 'digeut'),
('beginner', 'jamo', 4,  'ㄹ', 'ㄹ', 'rieul'),
('beginner', 'jamo', 5,  'ㅁ', 'ㅁ', 'mieum'),
('beginner', 'jamo', 6,  'ㅂ', 'ㅂ', 'bieup'),
('beginner', 'jamo', 7,  'ㅅ', 'ㅅ', 'siot'),
('beginner', 'jamo', 8,  'ㅇ', 'ㅇ', 'ieung'),
('beginner', 'jamo', 9,  'ㅈ', 'ㅈ', 'jieut'),
('beginner', 'jamo', 10, 'ㅊ', 'ㅊ', 'chieut'),
('beginner', 'jamo', 11, 'ㅋ', 'ㅋ', 'kieuk'),
('beginner', 'jamo', 12, 'ㅌ', 'ㅌ', 'tieut'),
('beginner', 'jamo', 13, 'ㅍ', 'ㅍ', 'pieup'),
('beginner', 'jamo', 14, 'ㅎ', 'ㅎ', 'hieut'),
('beginner', 'jamo', 15, 'ㅏ', 'ㅏ', 'a'),
('beginner', 'jamo', 16, 'ㅑ', 'ㅑ', 'ya'),
('beginner', 'jamo', 17, 'ㅓ', 'ㅓ', 'eo'),
('beginner', 'jamo', 18, 'ㅕ', 'ㅕ', 'yeo'),
('beginner', 'jamo', 19, 'ㅗ', 'ㅗ', 'o'),
('beginner', 'jamo', 20, 'ㅛ', 'ㅛ', 'yo'),
('beginner', 'jamo', 21, 'ㅜ', 'ㅜ', 'u'),
('beginner', 'jamo', 22, 'ㅠ', 'ㅠ', 'yu'),
('beginner', 'jamo', 23, 'ㅡ', 'ㅡ', 'eu'),
('beginner', 'jamo', 24, 'ㅣ', 'ㅣ', 'i'),
('beginner', 'jamo', 25, 'ㄲ', 'ㄲ', 'ssanggiyeok'),
('beginner', 'jamo', 26, 'ㄸ', 'ㄸ', 'ssangdigeut'),
('beginner', 'jamo', 27, 'ㅃ', 'ㅃ', 'ssangbieup'),
('beginner', 'jamo', 28, 'ㅆ', 'ㅆ', 'ssangsiot'),
('beginner', 'jamo', 29, 'ㅉ', 'ㅉ', 'ssangjieut'),
('beginner', 'jamo', 30, 'ㅐ', 'ㅐ', 'ae'),
('beginner', 'jamo', 31, 'ㅒ', 'ㅒ', 'yae'),
('beginner', 'jamo', 32, 'ㅔ', 'ㅔ', 'e'),
('beginner', 'jamo', 33, 'ㅖ', 'ㅖ', 'ye'),
('beginner', 'jamo', 34, 'ㅘ', 'ㅘ', 'wa'),
('beginner', 'jamo', 35, 'ㅙ', 'ㅙ', 'wae'),
('beginner', 'jamo', 36, 'ㅚ', 'ㅚ', 'oe'),
('beginner', 'jamo', 37, 'ㅝ', 'ㅝ', 'wo'),
('beginner', 'jamo', 38, 'ㅞ', 'ㅞ', 'we'),
('beginner', 'jamo', 39, 'ㅟ', 'ㅟ', 'wi'),
('beginner', 'jamo', 40, 'ㅢ', 'ㅢ', 'ui');

-- =============================================================================
-- Beginner — syllable (30)
-- CV 음절 중심
-- =============================================================================
INSERT INTO writing_practice_seed (writing_level, writing_practice_type, seq, prompt, answer, hint) VALUES
('beginner', 'syllable', 1,  '가', '가', NULL),
('beginner', 'syllable', 2,  '나', '나', NULL),
('beginner', 'syllable', 3,  '다', '다', NULL),
('beginner', 'syllable', 4,  '라', '라', NULL),
('beginner', 'syllable', 5,  '마', '마', NULL),
('beginner', 'syllable', 6,  '바', '바', NULL),
('beginner', 'syllable', 7,  '사', '사', NULL),
('beginner', 'syllable', 8,  '아', '아', NULL),
('beginner', 'syllable', 9,  '자', '자', NULL),
('beginner', 'syllable', 10, '차', '차', NULL),
('beginner', 'syllable', 11, '카', '카', NULL),
('beginner', 'syllable', 12, '타', '타', NULL),
('beginner', 'syllable', 13, '파', '파', NULL),
('beginner', 'syllable', 14, '하', '하', NULL),
('beginner', 'syllable', 15, '고', '고', NULL),
('beginner', 'syllable', 16, '노', '노', NULL),
('beginner', 'syllable', 17, '도', '도', NULL),
('beginner', 'syllable', 18, '로', '로', NULL),
('beginner', 'syllable', 19, '모', '모', NULL),
('beginner', 'syllable', 20, '보', '보', NULL),
('beginner', 'syllable', 21, '소', '소', NULL),
('beginner', 'syllable', 22, '오', '오', NULL),
('beginner', 'syllable', 23, '조', '조', NULL),
('beginner', 'syllable', 24, '초', '초', NULL),
('beginner', 'syllable', 25, '기', '기', NULL),
('beginner', 'syllable', 26, '니', '니', NULL),
('beginner', 'syllable', 27, '디', '디', NULL),
('beginner', 'syllable', 28, '리', '리', NULL),
('beginner', 'syllable', 29, '미', '미', NULL),
('beginner', 'syllable', 30, '비', '비', NULL);

-- =============================================================================
-- Beginner — word (30)
-- 일상어 2~3음절
-- =============================================================================
INSERT INTO writing_practice_seed (writing_level, writing_practice_type, seq, prompt, answer, hint) VALUES
('beginner', 'word', 1,  '가족',   '가족',   'family'),
('beginner', 'word', 2,  '학교',   '학교',   'school'),
('beginner', 'word', 3,  '사랑',   '사랑',   'love'),
('beginner', 'word', 4,  '친구',   '친구',   'friend'),
('beginner', 'word', 5,  '음식',   '음식',   'food'),
('beginner', 'word', 6,  '한국',   '한국',   'Korea'),
('beginner', 'word', 7,  '서울',   '서울',   'Seoul'),
('beginner', 'word', 8,  '시간',   '시간',   'time'),
('beginner', 'word', 9,  '사람',   '사람',   'person'),
('beginner', 'word', 10, '학생',   '학생',   'student'),
('beginner', 'word', 11, '엄마',   '엄마',   'mom'),
('beginner', 'word', 12, '아빠',   '아빠',   'dad'),
('beginner', 'word', 13, '나라',   '나라',   'country'),
('beginner', 'word', 14, '언어',   '언어',   'language'),
('beginner', 'word', 15, '이름',   '이름',   'name'),
('beginner', 'word', 16, '하루',   '하루',   'day'),
('beginner', 'word', 17, '주말',   '주말',   'weekend'),
('beginner', 'word', 18, '오늘',   '오늘',   'today'),
('beginner', 'word', 19, '내일',   '내일',   'tomorrow'),
('beginner', 'word', 20, '아침',   '아침',   'morning'),
('beginner', 'word', 21, '저녁',   '저녁',   'evening'),
('beginner', 'word', 22, '물',     '물',     'water'),
('beginner', 'word', 23, '밥',     '밥',     'rice'),
('beginner', 'word', 24, '차',     '차',     'tea'),
('beginner', 'word', 25, '집',     '집',     'house'),
('beginner', 'word', 26, '책',     '책',     'book'),
('beginner', 'word', 27, '돈',     '돈',     'money'),
('beginner', 'word', 28, '옷',     '옷',     'clothes'),
('beginner', 'word', 29, '꽃',     '꽃',     'flower'),
('beginner', 'word', 30, '하늘',   '하늘',   'sky');

-- =============================================================================
-- Intermediate — word (30)
-- 3~4음절 + 복합 단어
-- =============================================================================
INSERT INTO writing_practice_seed (writing_level, writing_practice_type, seq, prompt, answer, hint) VALUES
('intermediate', 'word', 1,  '연습',       '연습',       'practice'),
('intermediate', 'word', 2,  '공부',       '공부',       'study'),
('intermediate', 'word', 3,  '도서관',     '도서관',     'library'),
('intermediate', 'word', 4,  '병원',       '병원',       'hospital'),
('intermediate', 'word', 5,  '공항',       '공항',       'airport'),
('intermediate', 'word', 6,  '지하철',     '지하철',     'subway'),
('intermediate', 'word', 7,  '버스',       '버스',       'bus'),
('intermediate', 'word', 8,  '택시',       '택시',       'taxi'),
('intermediate', 'word', 9,  '커피숍',     '커피숍',     'coffee shop'),
('intermediate', 'word', 10, '음악회',     '음악회',     'concert'),
('intermediate', 'word', 11, '영화관',     '영화관',     'movie theater'),
('intermediate', 'word', 12, '운동장',     '운동장',     'sports field'),
('intermediate', 'word', 13, '회사원',     '회사원',     'office worker'),
('intermediate', 'word', 14, '가족사진',   '가족사진',   'family photo'),
('intermediate', 'word', 15, '부모님',     '부모님',     'parents'),
('intermediate', 'word', 16, '형제자매',   '형제자매',   'siblings'),
('intermediate', 'word', 17, '선생님',     '선생님',     'teacher'),
('intermediate', 'word', 18, '학생증',     '학생증',     'student ID'),
('intermediate', 'word', 19, '친구들',     '친구들',     'friends'),
('intermediate', 'word', 20, '직장인',     '직장인',     'office worker'),
('intermediate', 'word', 21, '취미생활',   '취미생활',   'hobby'),
('intermediate', 'word', 22, '요리법',     '요리법',     'recipe'),
('intermediate', 'word', 23, '청소기',     '청소기',     'vacuum cleaner'),
('intermediate', 'word', 24, '세탁기',     '세탁기',     'washing machine'),
('intermediate', 'word', 25, '쇼핑몰',     '쇼핑몰',     'shopping mall'),
('intermediate', 'word', 26, '여행가방',   '여행가방',   'luggage'),
('intermediate', 'word', 27, '휴가철',     '휴가철',     'vacation season'),
('intermediate', 'word', 28, '약속',       '약속',       'appointment'),
('intermediate', 'word', 29, '생일파티',   '생일파티',   'birthday party'),
('intermediate', 'word', 30, '결혼식',     '결혼식',     'wedding');

-- =============================================================================
-- Intermediate — sentence (30)
-- 기초 회화
-- =============================================================================
INSERT INTO writing_practice_seed (writing_level, writing_practice_type, seq, prompt, answer, hint) VALUES
('intermediate', 'sentence', 1,  '안녕하세요.',               '안녕하세요.',               NULL),
('intermediate', 'sentence', 2,  '반갑습니다.',               '반갑습니다.',               NULL),
('intermediate', 'sentence', 3,  '저는 학생입니다.',          '저는 학생입니다.',          NULL),
('intermediate', 'sentence', 4,  '이름이 뭐예요?',            '이름이 뭐예요?',            NULL),
('intermediate', 'sentence', 5,  '어디에서 왔어요?',          '어디에서 왔어요?',          NULL),
('intermediate', 'sentence', 6,  '한국어를 배우고 있어요.',    '한국어를 배우고 있어요.',    NULL),
('intermediate', 'sentence', 7,  '오늘 날씨가 좋네요.',       '오늘 날씨가 좋네요.',       NULL),
('intermediate', 'sentence', 8,  '밥 먹었어요?',              '밥 먹었어요?',              NULL),
('intermediate', 'sentence', 9,  '감사합니다.',               '감사합니다.',               NULL),
('intermediate', 'sentence', 10, '죄송합니다.',               '죄송합니다.',               NULL),
('intermediate', 'sentence', 11, '괜찮아요.',                 '괜찮아요.',                 NULL),
('intermediate', 'sentence', 12, '잘 부탁드립니다.',          '잘 부탁드립니다.',          NULL),
('intermediate', 'sentence', 13, '만나서 반가워요.',          '만나서 반가워요.',          NULL),
('intermediate', 'sentence', 14, '내일 봐요.',                '내일 봐요.',                NULL),
('intermediate', 'sentence', 15, '잘 지내세요?',              '잘 지내세요?',              NULL),
('intermediate', 'sentence', 16, '어떻게 지내셨어요?',        '어떻게 지내셨어요?',        NULL),
('intermediate', 'sentence', 17, '요즘 바쁘세요?',            '요즘 바쁘세요?',            NULL),
('intermediate', 'sentence', 18, '주말에 뭐 해요?',           '주말에 뭐 해요?',           NULL),
('intermediate', 'sentence', 19, '한국 음식 좋아해요?',       '한국 음식 좋아해요?',       NULL),
('intermediate', 'sentence', 20, '김치 먹어 봤어요?',         '김치 먹어 봤어요?',         NULL),
('intermediate', 'sentence', 21, '저는 커피를 좋아해요.',     '저는 커피를 좋아해요.',     NULL),
('intermediate', 'sentence', 22, '오늘은 좀 피곤해요.',       '오늘은 좀 피곤해요.',       NULL),
('intermediate', 'sentence', 23, '시간이 빨리 가네요.',       '시간이 빨리 가네요.',       NULL),
('intermediate', 'sentence', 24, '여기 앉아도 돼요?',         '여기 앉아도 돼요?',         NULL),
('intermediate', 'sentence', 25, '이거 얼마예요?',            '이거 얼마예요?',            NULL),
('intermediate', 'sentence', 26, '화장실이 어디예요?',        '화장실이 어디예요?',        NULL),
('intermediate', 'sentence', 27, '사진 찍어도 돼요?',         '사진 찍어도 돼요?',         NULL),
('intermediate', 'sentence', 28, '다시 말씀해 주세요.',       '다시 말씀해 주세요.',       NULL),
('intermediate', 'sentence', 29, '천천히 말해 주세요.',       '천천히 말해 주세요.',       NULL),
('intermediate', 'sentence', 30, '도와주셔서 감사합니다.',    '도와주셔서 감사합니다.',    NULL);

-- =============================================================================
-- Advanced — sentence (20)
-- 복문·경어법 포함
-- =============================================================================
INSERT INTO writing_practice_seed (writing_level, writing_practice_type, seq, prompt, answer, hint) VALUES
('advanced', 'sentence', 1,  '오늘 아침에 일찍 일어나서 공원을 한 바퀴 돌았습니다.',                                 '오늘 아침에 일찍 일어나서 공원을 한 바퀴 돌았습니다.',                                 NULL),
('advanced', 'sentence', 2,  '한국어 공부를 시작한 지 벌써 일 년이 되었습니다.',                                     '한국어 공부를 시작한 지 벌써 일 년이 되었습니다.',                                     NULL),
('advanced', 'sentence', 3,  '주말에는 친구들과 함께 맛있는 음식을 먹으러 갈 거예요.',                               '주말에는 친구들과 함께 맛있는 음식을 먹으러 갈 거예요.',                               NULL),
('advanced', 'sentence', 4,  '요즘 일이 너무 바빠서 운동할 시간이 없어요.',                                          '요즘 일이 너무 바빠서 운동할 시간이 없어요.',                                          NULL),
('advanced', 'sentence', 5,  '저는 한국 드라마를 보면서 한국어를 배우고 있어요.',                                     '저는 한국 드라마를 보면서 한국어를 배우고 있어요.',                                     NULL),
('advanced', 'sentence', 6,  '비가 오는 날에는 따뜻한 차를 마시는 게 좋아요.',                                       '비가 오는 날에는 따뜻한 차를 마시는 게 좋아요.',                                       NULL),
('advanced', 'sentence', 7,  '지하철이 버스보다 더 빠르고 편리해요.',                                                '지하철이 버스보다 더 빠르고 편리해요.',                                                NULL),
('advanced', 'sentence', 8,  '한국의 사계절은 각각 다른 매력을 가지고 있습니다.',                                    '한국의 사계절은 각각 다른 매력을 가지고 있습니다.',                                    NULL),
('advanced', 'sentence', 9,  '한국 음식 중에서 저는 비빔밥을 제일 좋아합니다.',                                      '한국 음식 중에서 저는 비빔밥을 제일 좋아합니다.',                                      NULL),
('advanced', 'sentence', 10, '내년에는 꼭 한국에 여행을 가 보고 싶습니다.',                                          '내년에는 꼭 한국에 여행을 가 보고 싶습니다.',                                          NULL),
('advanced', 'sentence', 11, '새로운 사람들을 만나는 것은 항상 즐거운 일입니다.',                                    '새로운 사람들을 만나는 것은 항상 즐거운 일입니다.',                                    NULL),
('advanced', 'sentence', 12, '건강을 위해서 규칙적으로 운동을 해야 합니다.',                                         '건강을 위해서 규칙적으로 운동을 해야 합니다.',                                         NULL),
('advanced', 'sentence', 13, '한국어 능력 시험을 준비하고 있어요.',                                                  '한국어 능력 시험을 준비하고 있어요.',                                                  NULL),
('advanced', 'sentence', 14, '저는 매일 한 시간씩 한국어를 공부합니다.',                                             '저는 매일 한 시간씩 한국어를 공부합니다.',                                             NULL),
('advanced', 'sentence', 15, '한국 문화에 대해 더 많이 알고 싶어요.',                                                '한국 문화에 대해 더 많이 알고 싶어요.',                                                NULL),
('advanced', 'sentence', 16, '서울은 낮과 밤이 모두 아름다운 도시예요.',                                             '서울은 낮과 밤이 모두 아름다운 도시예요.',                                             NULL),
('advanced', 'sentence', 17, '외국어를 배우는 것은 시간과 노력이 필요합니다.',                                       '외국어를 배우는 것은 시간과 노력이 필요합니다.',                                       NULL),
('advanced', 'sentence', 18, '한국 사람들은 정이 많고 친절해요.',                                                    '한국 사람들은 정이 많고 친절해요.',                                                    NULL),
('advanced', 'sentence', 19, '봄에는 벚꽃이, 가을에는 단풍이 아름답습니다.',                                         '봄에는 벚꽃이, 가을에는 단풍이 아름답습니다.',                                         NULL),
('advanced', 'sentence', 20, '저는 조용한 카페에서 책 읽는 것을 좋아해요.',                                          '저는 조용한 카페에서 책 읽는 것을 좋아해요.',                                          NULL);

-- =============================================================================
-- Advanced — paragraph (10)
-- 2~4문장으로 구성된 짧은 문단
-- =============================================================================
INSERT INTO writing_practice_seed (writing_level, writing_practice_type, seq, prompt, answer, hint) VALUES
('advanced', 'paragraph', 1,
 '저는 매일 아침 일찍 일어나서 운동을 합니다. 운동을 하고 나면 샤워를 하고 아침을 먹습니다. 그 다음에 회사로 출근해서 하루를 시작합니다.',
 '저는 매일 아침 일찍 일어나서 운동을 합니다. 운동을 하고 나면 샤워를 하고 아침을 먹습니다. 그 다음에 회사로 출근해서 하루를 시작합니다.',
 NULL),
('advanced', 'paragraph', 2,
 '한국어는 배우기 어려운 언어라고 알려져 있지만, 꾸준히 노력하면 누구나 배울 수 있습니다. 중요한 것은 매일 조금씩이라도 공부하는 것입니다.',
 '한국어는 배우기 어려운 언어라고 알려져 있지만, 꾸준히 노력하면 누구나 배울 수 있습니다. 중요한 것은 매일 조금씩이라도 공부하는 것입니다.',
 NULL),
('advanced', 'paragraph', 3,
 '서울은 밤이 되면 더욱 아름다워지는 도시입니다. 한강을 따라 걸으면서 야경을 감상하는 것은 정말 특별한 경험입니다.',
 '서울은 밤이 되면 더욱 아름다워지는 도시입니다. 한강을 따라 걸으면서 야경을 감상하는 것은 정말 특별한 경험입니다.',
 NULL),
('advanced', 'paragraph', 4,
 '한국의 사계절은 각각의 매력이 있습니다. 봄에는 벚꽃이 피고, 여름에는 바다에서 수영을 즐길 수 있습니다. 가을에는 단풍이 아름답고, 겨울에는 눈이 내려서 스키를 탈 수 있습니다.',
 '한국의 사계절은 각각의 매력이 있습니다. 봄에는 벚꽃이 피고, 여름에는 바다에서 수영을 즐길 수 있습니다. 가을에는 단풍이 아름답고, 겨울에는 눈이 내려서 스키를 탈 수 있습니다.',
 NULL),
('advanced', 'paragraph', 5,
 '김치는 한국을 대표하는 음식입니다. 배추, 고춧가루, 마늘 등 여러 가지 재료로 만들어지며 맛과 영양이 풍부합니다. 한국 사람들은 매 끼니마다 김치를 먹습니다.',
 '김치는 한국을 대표하는 음식입니다. 배추, 고춧가루, 마늘 등 여러 가지 재료로 만들어지며 맛과 영양이 풍부합니다. 한국 사람들은 매 끼니마다 김치를 먹습니다.',
 NULL),
('advanced', 'paragraph', 6,
 '한국의 전통 명절 중에서 가장 큰 명절은 설날과 추석입니다. 설날에는 가족이 모여 떡국을 먹고 세배를 합니다. 추석에는 송편을 만들어 먹습니다.',
 '한국의 전통 명절 중에서 가장 큰 명절은 설날과 추석입니다. 설날에는 가족이 모여 떡국을 먹고 세배를 합니다. 추석에는 송편을 만들어 먹습니다.',
 NULL),
('advanced', 'paragraph', 7,
 '제가 한국어를 배우기 시작한 이유는 한국 드라마를 너무 좋아했기 때문입니다. 자막 없이 드라마를 보고 싶다는 꿈을 이루기 위해 열심히 공부하고 있습니다.',
 '제가 한국어를 배우기 시작한 이유는 한국 드라마를 너무 좋아했기 때문입니다. 자막 없이 드라마를 보고 싶다는 꿈을 이루기 위해 열심히 공부하고 있습니다.',
 NULL),
('advanced', 'paragraph', 8,
 '외국어를 배우는 가장 좋은 방법은 그 나라의 문화를 함께 경험하는 것입니다. 음식, 음악, 영화 등을 통해 자연스럽게 언어를 접하면 공부가 훨씬 재미있어집니다.',
 '외국어를 배우는 가장 좋은 방법은 그 나라의 문화를 함께 경험하는 것입니다. 음식, 음악, 영화 등을 통해 자연스럽게 언어를 접하면 공부가 훨씬 재미있어집니다.',
 NULL),
('advanced', 'paragraph', 9,
 '오늘날 많은 사람들이 스마트폰으로 언어를 배웁니다. 앱을 이용하면 언제 어디서나 쉽게 공부할 수 있기 때문입니다. 하지만 가장 중요한 것은 꾸준함입니다.',
 '오늘날 많은 사람들이 스마트폰으로 언어를 배웁니다. 앱을 이용하면 언제 어디서나 쉽게 공부할 수 있기 때문입니다. 하지만 가장 중요한 것은 꾸준함입니다.',
 NULL),
('advanced', 'paragraph', 10,
 '한국의 대중교통은 매우 편리하고 잘 발달되어 있습니다. 지하철과 버스 노선이 촘촘하게 연결되어 있어서 어디든 쉽게 갈 수 있습니다. 교통카드 하나만 있으면 지하철과 버스를 모두 이용할 수 있어요.',
 '한국의 대중교통은 매우 편리하고 잘 발달되어 있습니다. 지하철과 버스 노선이 촘촘하게 연결되어 있어서 어디든 쉽게 갈 수 있습니다. 교통카드 하나만 있으면 지하철과 버스를 모두 이용할 수 있어요.',
 NULL);
