CREATE TABLE IF NOT EXISTS admin_action_log (
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL,
  action_type VARCHAR(50) NOT NULL,
  target_table VARCHAR(50),
  target_id BIGINT,
  details JSONB,
  ip_address INET,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);