-- 1. 기존 테이블 정리
DROP TABLE IF EXISTS "study_task_log";
DROP TABLE IF EXISTS "study_task_status";

-- 2. Enum 값 추가 (Enum 타입이 이미 존재한다고 가정)
ALTER TYPE study_task_log_action_enum ADD VALUE IF NOT EXISTS 'status';

-- 3. 컬럼명 변경
ALTER TABLE "study_task_choice" 
RENAME COLUMN "study_task_choice_correct" TO "study_task_choice_answer";

-- 4. Status 테이블 (Current Snapshot)
CREATE TABLE "study_task_status" (
  "study_task_id"                 INT NOT NULL, 
  "user_id"                       BIGINT NOT NULL REFERENCES "users"("user_id") ON DELETE CASCADE,
  "study_task_status_try_count"   INT NOT NULL DEFAULT 0,       
  "study_task_status_is_solved"   BOOLEAN NOT NULL DEFAULT false, 
  "study_task_status_last_attempt_at" TIMESTAMPTZ DEFAULT (now()),

  CONSTRAINT "fk_study_task_status_task" FOREIGN KEY ("study_task_id") REFERENCES "study_task"("study_task_id") ON DELETE CASCADE
);

-- 5. Log 테이블 (History)
CREATE TABLE "study_task_log" (
  "study_task_log_id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "study_task_id"               INT NOT NULL,
  "user_id"                     BIGINT NOT NULL REFERENCES "users"("user_id") ON DELETE CASCADE,
  "login_id"                    BIGINT NOT NULL,
  "study_task_action_log"       study_task_log_action_enum NOT NULL, 
  "study_task_try_no_log"       INT NOT NULL DEFAULT 1, 
  "study_task_is_correct_log"   BOOLEAN,
  "study_task_answer_log"       JSONB, 
  "study_task_created_at_log"   TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "study_task_ip_log"           INET,
  "study_task_device_log"       login_device_enum,
  "study_task_user_agent_log"   JSONB,

  CONSTRAINT "fk_study_task_log_task" FOREIGN KEY ("study_task_id") REFERENCES "study_task"("study_task_id") ON DELETE CASCADE
);

-- 6. [보완] 성능 향상을 위한 인덱스 (필수)
-- 목적: "내(user_id)가 이 문제(study_task_id)를 예전에 어떻게 풀었지?" 조회용
CREATE INDEX "idx_study_task_log_user_task" ON "study_task_log" ("user_id", "study_task_id");