-- Course 도메인 마이그레이션 (2026-02-02)
-- 결제 후 콘텐츠(lesson) 접근을 관리하는 코스 테이블

-- =========================================================================
-- 1. ENUM Types
-- =========================================================================

-- 코스 타입: 영상 강좌, 학습 문제, 실시간 강의, 패키지(묶음)
CREATE TYPE course_type_enum AS ENUM ('video', 'study', 'live', 'package');

-- 코스 상태: 활성, 비활성, 삭제됨
CREATE TYPE course_state_enum AS ENUM ('active', 'inactive', 'deleted');

-- =========================================================================
-- 2. Tables
-- =========================================================================

-- course: 코스(수강권) 기본 정보
CREATE TABLE course (
  course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_by_user_id BIGINT NOT NULL,
  -- 식별 및 기본 정보
  course_idx VARCHAR(100) UNIQUE NOT NULL,      -- 비즈니스 식별 코드 (예: COURSE-001)
  course_title VARCHAR(150) NOT NULL,           -- 코스 제목
  course_subtitle VARCHAR(250),                 -- 부제목
  course_description TEXT,                      -- 상세 설명
  -- 상태 및 분류
  course_type course_type_enum NOT NULL DEFAULT 'video',
  course_state course_state_enum NOT NULL DEFAULT 'inactive',
  -- 가격 정보
  course_price INT NOT NULL DEFAULT 0,          -- 가격 (원)
  course_discount_price INT,                    -- 할인가
  course_currency VARCHAR(3) NOT NULL DEFAULT 'KRW',
  -- 유효 기간 (일 단위, NULL이면 무제한)
  course_valid_days INT,
  -- 메타 정보
  course_thumbnail_url TEXT,
  course_preview_url TEXT,                      -- 미리보기 영상 URL
  -- 감사 추적
  course_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  course_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- course_lesson: 코스-레슨 매핑 (하나의 코스에 여러 레슨 포함)
CREATE TABLE course_lesson (
  course_id INT NOT NULL,
  lesson_id INT NOT NULL,
  course_lesson_seq INT NOT NULL DEFAULT 1,     -- 코스 내 레슨 순서
  course_lesson_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (course_id, lesson_id)
);

-- user_course: 사용자 수강권 (구매/부여된 코스)
CREATE TABLE user_course (
  user_course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  course_id INT NOT NULL,
  -- 수강 상태
  user_course_active BOOLEAN NOT NULL DEFAULT true,  -- 수강 활성 여부
  -- 유효 기간
  user_course_start_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_course_expire_at TIMESTAMPTZ,            -- NULL이면 무제한
  -- 진행 정보
  user_course_progress_percent INT NOT NULL DEFAULT 0,  -- 전체 진도율 (0-100)
  user_course_last_lesson_id INT,               -- 마지막 학습 레슨
  user_course_last_progress_at TIMESTAMPTZ,
  -- 구매/부여 정보
  user_course_granted_by_user_id BIGINT,        -- 부여한 관리자 (수동 부여 시)
  user_course_pay_id BIGINT,                    -- 결제 ID (결제 시스템 연동 시)
  -- 감사 추적
  user_course_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_course_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- admin_course_log: 코스 관리 감사 로그
CREATE TABLE admin_course_log (
  admin_course_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id BIGINT NOT NULL,
  admin_pick_course_id INT,
  admin_pick_user_course_id BIGINT,
  admin_course_action admin_action_enum NOT NULL,
  admin_course_before JSONB,
  admin_course_after JSONB,
  admin_course_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  admin_course_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- 3. Foreign Keys
-- =========================================================================

ALTER TABLE course
  ADD FOREIGN KEY (updated_by_user_id) REFERENCES users (user_id);

ALTER TABLE course_lesson
  ADD FOREIGN KEY (course_id) REFERENCES course (course_id) ON DELETE CASCADE;
ALTER TABLE course_lesson
  ADD FOREIGN KEY (lesson_id) REFERENCES lesson (lesson_id) ON DELETE CASCADE;

ALTER TABLE user_course
  ADD FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE user_course
  ADD FOREIGN KEY (course_id) REFERENCES course (course_id) ON DELETE CASCADE;
ALTER TABLE user_course
  ADD FOREIGN KEY (user_course_last_lesson_id) REFERENCES lesson (lesson_id);
ALTER TABLE user_course
  ADD FOREIGN KEY (user_course_granted_by_user_id) REFERENCES users (user_id);

ALTER TABLE admin_course_log
  ADD FOREIGN KEY (admin_user_id) REFERENCES users (user_id);
ALTER TABLE admin_course_log
  ADD FOREIGN KEY (admin_pick_course_id) REFERENCES course (course_id);
ALTER TABLE admin_course_log
  ADD FOREIGN KEY (admin_pick_user_course_id) REFERENCES user_course (user_course_id);

-- =========================================================================
-- 4. Indexes
-- =========================================================================

-- course: 상태/타입 기반 필터링
CREATE INDEX idx_course_state ON course (course_state);
CREATE INDEX idx_course_type ON course (course_type);
CREATE INDEX idx_course_state_type ON course (course_state, course_type);

-- course_lesson: 코스별 레슨 조회
CREATE INDEX idx_course_lesson_course_id ON course_lesson (course_id);
CREATE INDEX idx_course_lesson_lesson_id ON course_lesson (lesson_id);
CREATE UNIQUE INDEX unique_course_lesson_seq ON course_lesson (course_id, course_lesson_seq);

-- user_course: 사용자별 수강권 조회
CREATE INDEX idx_user_course_user_id ON user_course (user_id);
CREATE INDEX idx_user_course_course_id ON user_course (course_id);
CREATE INDEX idx_user_course_active ON user_course (user_course_active);
CREATE INDEX idx_user_course_expire ON user_course (user_course_expire_at);
CREATE UNIQUE INDEX unique_user_course ON user_course (user_id, course_id);

-- admin_course_log: 감사 로그 검색
CREATE INDEX idx_admin_course_log_admin ON admin_course_log (admin_user_id);
CREATE INDEX idx_admin_course_log_course ON admin_course_log (admin_pick_course_id);
CREATE INDEX idx_admin_course_log_user_course ON admin_course_log (admin_pick_user_course_id);

-- =========================================================================
-- 5. Comments
-- =========================================================================

COMMENT ON TABLE course IS '코스(수강권) - 여러 레슨을 묶은 상품 단위';
COMMENT ON TABLE course_lesson IS '코스-레슨 매핑 테이블';
COMMENT ON TABLE user_course IS '사용자별 수강권 (구매/부여된 코스)';
COMMENT ON TABLE admin_course_log IS '코스 관리 감사 로그';

COMMENT ON COLUMN course.course_valid_days IS '수강 유효 기간 (일). NULL이면 무제한';
COMMENT ON COLUMN user_course.user_course_expire_at IS '수강 만료일. NULL이면 무제한';
COMMENT ON COLUMN user_course.user_course_pay_id IS '결제 ID (pay 테이블 연동 시 사용)';
