-- =============================================================================
-- 설명(해설) 콘텐츠 테이블 — explanation_unit / explanation_block
-- =============================================================================
-- 출처: books→api 인계 (amazing-korean-books/docs/guide/explanation_handoff_to_api.md)
-- 설계: AMK_API_LEARNING.md §5.10 (B안 — content_translations 무변경)
-- 같은 날 다중 마이그레이션 = 다음 날짜 사용 관례 (migrations/README.md §1).
-- =============================================================================

-- 1. 신규 enum -----------------------------------------------------------------

CREATE TYPE explanation_unit_kind_enum AS ENUM ('pattern_guide', 'sentence_explain');

CREATE TYPE explanation_source_enum AS ENUM ('guide_67', 'tense_v1', 'josa_v1');

CREATE TYPE explanation_block_type_enum AS ENUM (
    'heading', 'subtitle', 'paragraph', 'step', 'table', 'example',
    'note', 'concept_card', 'qword_card', 'structured_explain', 'diagram'
);

-- 2. explanation_unit ----------------------------------------------------------

CREATE TABLE explanation_unit (
    explanation_unit_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_by_user_id           bigint,                                   -- nullable: 시스템 시드 콘텐츠 = NULL (lesson/study 컨벤션 동일). 관리자 편집 시 채움
    unit_idx                     varchar(100) NOT NULL,                    -- books unit_id = 재시딩 멱등 키
    unit_seq                     int NOT NULL,                             -- 원본 문서 순서 보존
    unit_kind                    explanation_unit_kind_enum NOT NULL,
    unit_source                  explanation_source_enum NOT NULL,
    -- 외부 연결키 (논리 참조, FK 아님 — tense_v1/josa_v1 무링크 / av_307_313 갭 / 시딩 순서 독립)
    study_idx                    varchar(100),                             -- → study.study_idx (pattern_guide 68)
    study_task_idx               varchar(100),                             -- → study_task.study_task_idx = amk500-sent-NNN (sentence_explain 500)
    sentence_num                 int,
    section_id                   varchar(50),
    link_meta                    jsonb,                                    -- pattern_id/sentence_range/section_code/sub_code (참조용, 저빈도)
    -- title / subtitle (LocalizedText 평면화, 방식 ㉠)
    title_ko                     text,                                     -- nullable (guide_67 ko = best-effort)
    title_en                     text,                                     -- 권위 텍스트
    title_lang_invariant         boolean NOT NULL DEFAULT false,
    subtitle_ko                  text,
    subtitle_en                  text,
    subtitle_lang_invariant      boolean NOT NULL DEFAULT false,
    explanation_unit_created_at  timestamptz NOT NULL DEFAULT (now()),
    explanation_unit_updated_at  timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE explanation_unit ADD FOREIGN KEY (updated_by_user_id) REFERENCES users (user_id);

CREATE UNIQUE INDEX uq_explanation_unit_idx          ON explanation_unit (unit_idx);
CREATE INDEX        idx_explanation_unit_study_idx   ON explanation_unit (study_idx)      WHERE study_idx IS NOT NULL;
CREATE INDEX        idx_explanation_unit_task_idx    ON explanation_unit (study_task_idx) WHERE study_task_idx IS NOT NULL;

COMMENT ON TABLE  explanation_unit              IS '해설(설명) 콘텐츠 교육 단위. books→api 인계 (AMK_API_LEARNING.md §5.10).';
COMMENT ON COLUMN explanation_unit.unit_idx     IS 'books unit_id (예: guide67:pr_105_114) — 재시딩 멱등 + content_translations 해소 키';
COMMENT ON COLUMN explanation_unit.study_idx    IS '논리 참조 → study.study_idx (FK 아님, 시드 후 정합 검증)';
COMMENT ON COLUMN explanation_unit.study_task_idx IS '논리 참조 → study_task.study_task_idx = amk500-sent-NNN (FK 아님)';

-- 3. explanation_block ---------------------------------------------------------

CREATE TABLE explanation_block (
    explanation_block_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    explanation_unit_id          int NOT NULL REFERENCES explanation_unit(explanation_unit_id) ON DELETE CASCADE,
    block_seq                    int NOT NULL,                             -- unit 내 순서 보존
    block_type                   explanation_block_type_enum NOT NULL,
    block_level                  smallint,                                 -- heading 2/3/4 (nullable)
    text_ko                      text,
    text_en                      text,
    text_lang_invariant          boolean NOT NULL DEFAULT false,
    raw                          text,                                     -- lang-invariant 원형 (table/pre/diagram HTML, ko)
    structured                   jsonb,                                    -- structured_explain rows/header/note/extra + concept_card/qword_card items (lang-invariant 골격)
    explanation_block_created_at timestamptz NOT NULL DEFAULT (now()),
    explanation_block_updated_at timestamptz NOT NULL DEFAULT (now()),
    UNIQUE (explanation_unit_id, block_seq)
);

COMMENT ON TABLE  explanation_block            IS '해설 콘텐츠 블록 (순서 보존). 번역 대상 텍스트는 content_translations 튜플 분리, lang-invariant 골격은 structured/raw 보관.';
COMMENT ON COLUMN explanation_block.structured IS 'lang-invariant 골격 (rows role/form 등). 번역 대상은 content_translations (field_name=explanation_block_row_{i}_*).';
