-- i18n 다국어 콘텐츠 번역 인프라 (Phase 1A)
-- 21개 언어 지원 (아랍어 제외), content_translations 정규화 테이블

-- ============================================================
-- 1. 신규 ENUM 타입
-- ============================================================

CREATE TYPE content_type_enum AS ENUM (
    'course',
    'lesson',
    'video_tag',
    'study',
    'study_task_choice',
    'study_task_typing',
    'study_task_voice'
);

CREATE TYPE translation_status_enum AS ENUM (
    'draft',
    'reviewed',
    'approved'
);

CREATE TYPE supported_language_enum AS ENUM (
    'ko', 'en', 'ja', 'zh_cn', 'zh_tw',
    'vi', 'th', 'id', 'my', 'mn', 'ru',
    'es', 'pt', 'fr', 'de', 'hi', 'ne',
    'si', 'km', 'uz', 'kk', 'tg'
);

-- ============================================================
-- 2. 기존 ENUM 확장 (user_language_enum: ko, en → +19개)
-- ============================================================

ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'ja';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'zh_cn';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'zh_tw';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'vi';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'th';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'id';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'my';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'mn';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'ru';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'es';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'pt';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'fr';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'de';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'hi';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'ne';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'si';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'km';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'uz';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'kk';
ALTER TYPE user_language_enum ADD VALUE IF NOT EXISTS 'tg';

-- ============================================================
-- 3. 기존 ENUM 확장 (user_set_language_enum: ko, en → +19개)
-- ============================================================

ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'ja';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'zh_cn';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'zh_tw';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'vi';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'th';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'id';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'my';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'mn';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'ru';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'es';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'pt';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'fr';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'de';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'hi';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'ne';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'si';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'km';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'uz';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'kk';
ALTER TYPE user_set_language_enum ADD VALUE IF NOT EXISTS 'tg';

-- ============================================================
-- 4. content_translations 테이블
-- ============================================================

CREATE TABLE content_translations (
    translation_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type     content_type_enum NOT NULL,
    content_id       BIGINT NOT NULL,
    field_name       VARCHAR(100) NOT NULL,
    lang             supported_language_enum NOT NULL,
    translated_text  TEXT NOT NULL,
    status           translation_status_enum NOT NULL DEFAULT 'draft',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_ct_content_field_lang UNIQUE (content_type, content_id, field_name, lang)
);

-- 콘텐츠별 번역 조회 (fallback 쿼리에서 사용)
CREATE INDEX idx_ct_lookup ON content_translations (content_type, content_id, lang);

-- 상태별 필터링 (관리자 검수 대기 목록 등)
CREATE INDEX idx_ct_status ON content_translations (status);
