-- =============================================================================
-- 한글 자판 연습 (Writing Practice) — study_task_writing + writing_practice_session
-- =============================================================================

-- 1. Enum 확장 / 신규 생성
-- -----------------------------------------------------------------------------
ALTER TYPE study_task_kind_enum ADD VALUE IF NOT EXISTS 'writing';
ALTER TYPE content_type_enum ADD VALUE IF NOT EXISTS 'study_task_writing';

CREATE TYPE writing_level_enum AS ENUM ('beginner', 'intermediate', 'advanced');
CREATE TYPE writing_practice_type_enum AS ENUM ('jamo', 'syllable', 'word', 'sentence', 'paragraph');

-- 2. study_task_writing (서브테이블: PK = study_task_id FK → study_task)
-- -----------------------------------------------------------------------------
CREATE TABLE study_task_writing (
    study_task_id                       INT PRIMARY KEY,
    study_task_writing_level            writing_level_enum NOT NULL DEFAULT 'beginner',
    study_task_writing_practice_type    writing_practice_type_enum NOT NULL DEFAULT 'word',
    study_task_writing_prompt           TEXT NOT NULL,
    study_task_writing_answer           TEXT NOT NULL,
    study_task_writing_hint             TEXT,
    study_task_writing_keyboard_visible BOOLEAN NOT NULL DEFAULT TRUE,
    study_task_writing_image_url        TEXT,
    study_task_writing_audio_url        TEXT,

    CONSTRAINT fk_study_task_writing_task
        FOREIGN KEY (study_task_id) REFERENCES study_task (study_task_id)
);

CREATE INDEX idx_stw_level
    ON study_task_writing (study_task_writing_level);
CREATE INDEX idx_stw_practice_type
    ON study_task_writing (study_task_writing_practice_type);
CREATE INDEX idx_stw_level_type
    ON study_task_writing (study_task_writing_level, study_task_writing_practice_type);

-- 3. writing_practice_session (연습 통계, 독립 테이블)
-- -----------------------------------------------------------------------------
CREATE TABLE writing_practice_session (
    session_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL,
    study_task_id           INT,
    writing_level           writing_level_enum NOT NULL,
    writing_practice_type   writing_practice_type_enum NOT NULL,
    started_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at             TIMESTAMPTZ,
    total_chars             INT NOT NULL DEFAULT 0,
    correct_chars           INT NOT NULL DEFAULT 0,
    accuracy_rate           NUMERIC(5,2) NOT NULL DEFAULT 0.00,
    chars_per_minute        NUMERIC(7,2) NOT NULL DEFAULT 0.00,
    mistakes                JSONB NOT NULL DEFAULT '[]'::JSONB,

    CONSTRAINT fk_wps_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_wps_task
        FOREIGN KEY (study_task_id) REFERENCES study_task (study_task_id) ON DELETE SET NULL
);

CREATE INDEX idx_wps_user_id
    ON writing_practice_session (user_id);
CREATE INDEX idx_wps_user_level
    ON writing_practice_session (user_id, writing_level);
CREATE INDEX idx_wps_user_started
    ON writing_practice_session (user_id, started_at DESC);
CREATE INDEX idx_wps_task
    ON writing_practice_session (study_task_id);
