-- ============================================================================
-- Migration: 20260203_ADD_OAUTH_SUPPORT.sql
-- Description: Google OAuth 소셜 로그인 지원을 위한 스키마 변경
-- ============================================================================

-- 1. OAuth 계정 연동 테이블
-- 사용자와 OAuth Provider 간의 연결 정보 저장 (1:N 관계)
-- 향후 Apple 등 다른 OAuth Provider 추가 용이
CREATE TABLE user_oauth (
    user_oauth_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    oauth_provider login_method_enum NOT NULL,  -- 'google', 'apple' 등 (기존 ENUM 재사용)
    oauth_subject VARCHAR(255) NOT NULL,        -- OAuth Provider의 고유 사용자 ID (Google의 'sub' 클레임)
    oauth_email VARCHAR(255),                   -- OAuth에서 받은 이메일 (참고용, 변경될 수 있음)
    oauth_name VARCHAR(255),                    -- OAuth에서 받은 이름 (참고용)
    oauth_picture_url TEXT,                     -- 프로필 이미지 URL
    oauth_linked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),  -- 연결 시점
    oauth_last_login_at TIMESTAMPTZ,            -- 마지막 OAuth 로그인 시점
    -- 외래키: 사용자 삭제 시 OAuth 연결도 삭제
    CONSTRAINT fk_user_oauth_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    -- 고유 제약: 같은 Provider의 같은 subject는 한 번만 연결 가능
    CONSTRAINT unique_oauth_provider_subject UNIQUE (oauth_provider, oauth_subject)
);

-- 인덱스: 사용자별 OAuth 연결 조회
CREATE INDEX idx_user_oauth_user_id ON user_oauth(user_id);

-- 2. user_password NULL 허용
-- 소셜 로그인 전용 사용자는 비밀번호가 없음
ALTER TABLE users ALTER COLUMN user_password DROP NOT NULL;

-- 3. 코멘트 추가
COMMENT ON TABLE user_oauth IS 'OAuth Provider 연결 정보 (Google, Apple 등)';
COMMENT ON COLUMN user_oauth.oauth_subject IS 'OAuth Provider의 고유 사용자 ID (Google sub 클레임)';
COMMENT ON COLUMN user_oauth.oauth_email IS 'OAuth에서 받은 이메일 (변경될 수 있어 참고용)';
