-- ============================================================
-- E-book Web Viewer (Phase 12.5) — 2026-03-10
-- ============================================================

-- 1. ENUM Types
CREATE TYPE ebook_edition_enum AS ENUM ('student', 'teacher');
CREATE TYPE ebook_purchase_status_enum AS ENUM ('pending', 'completed', 'refunded');
CREATE TYPE ebook_payment_method_enum AS ENUM ('paddle', 'bank_transfer');

-- 2. ebook_purchase — 구매 기록
CREATE TABLE ebook_purchase (
  purchase_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_code     VARCHAR(20) UNIQUE NOT NULL,           -- EB-YYMMDD-NNNN
  user_id           BIGINT NOT NULL REFERENCES users(user_id),
  language          textbook_language_enum NOT NULL,        -- 기존 enum 재활용
  edition           ebook_edition_enum NOT NULL,
  payment_method    ebook_payment_method_enum NOT NULL,
  status            ebook_purchase_status_enum NOT NULL DEFAULT 'pending',
  price             INT NOT NULL,                          -- KRW
  currency          VARCHAR(3) NOT NULL DEFAULT 'KRW',
  paddle_txn_id     VARCHAR(100),                          -- Paddle transaction ID
  is_deleted        BOOLEAN NOT NULL DEFAULT false,
  deleted_at        TIMESTAMPTZ,
  completed_at      TIMESTAMPTZ,
  refunded_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. ebook_access_log — 페이지 조회 감사 로그
CREATE TABLE ebook_access_log (
  log_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id      BIGINT NOT NULL REFERENCES ebook_purchase(purchase_id) ON DELETE RESTRICT,
  user_id          BIGINT NOT NULL REFERENCES users(user_id),
  page_number      INT NOT NULL,
  watermark_id     VARCHAR(64),
  ip_address       INET,
  user_agent       TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. admin_ebook_log — 관리자 작업 기록
CREATE TABLE admin_ebook_log (
  log_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id    BIGINT NOT NULL REFERENCES users(user_id),
  purchase_id      BIGINT NOT NULL REFERENCES ebook_purchase(purchase_id) ON DELETE RESTRICT,
  action           admin_action_enum NOT NULL,
  before_data      JSONB,
  after_data       JSONB,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Indexes
CREATE INDEX idx_ebook_purchase_user ON ebook_purchase(user_id);
CREATE INDEX idx_ebook_purchase_code ON ebook_purchase(purchase_code);
CREATE INDEX idx_ebook_purchase_status ON ebook_purchase(status);
CREATE INDEX idx_ebook_purchase_created ON ebook_purchase(created_at DESC);
CREATE INDEX idx_ebook_access_purchase ON ebook_access_log(purchase_id);
CREATE INDEX idx_ebook_access_created ON ebook_access_log(created_at DESC);
