-- Textbook Order System Migration (2026-02-26)
-- 교재 주문 시스템을 위한 ENUM 타입 및 테이블 생성

-- =============================================================================
-- 1. New ENUM Types
-- =============================================================================

CREATE TYPE textbook_language_enum AS ENUM (
    'ja',       -- 일본어
    'zh_cn',    -- 중국어(간체)
    'zh_tw',    -- 중국어(번체)
    'vi',       -- 베트남어
    'th',       -- 태국어
    'id',       -- 인도네시아어
    'my',       -- 미얀마어
    'mn',       -- 몽골어
    'ru',       -- 러시아어
    'es',       -- 스페인어
    'pt',       -- 포르투갈어
    'fr',       -- 프랑스어
    'de',       -- 독일어
    'hi',       -- 힌디어
    'ne',       -- 네팔어
    'si',       -- 싱할라어
    'km',       -- 크메르어
    'uz',       -- 우즈베크어
    'kk',       -- 카자흐어
    'tg'        -- 타지크어
);

CREATE TYPE textbook_type_enum AS ENUM (
    'student',  -- 학생용
    'teacher'   -- 교사용
);

CREATE TYPE textbook_order_status_enum AS ENUM (
    'pending',      -- 주문 접수 (기본)
    'confirmed',    -- 관리자 확인
    'paid',         -- 입금 확인
    'printing',     -- 인쇄 중
    'shipped',      -- 발송 완료
    'delivered',    -- 배송 완료
    'canceled'      -- 취소
);

CREATE TYPE textbook_payment_method_enum AS ENUM (
    'bank_transfer' -- 계좌이체
    -- 추후: 'card', 'paddle' 추가
);

-- =============================================================================
-- 2. textbook : 교재 주문 기본 정보
-- =============================================================================
CREATE TABLE textbook (
    order_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code           VARCHAR(20) UNIQUE NOT NULL,       -- 외부 공개용 주문번호 (TB-YYMMDD-NNNN)
    status               textbook_order_status_enum NOT NULL DEFAULT 'pending',
    -- 신청자 정보
    orderer_name         VARCHAR(100) NOT NULL,             -- 신청자명
    orderer_email        VARCHAR(255) NOT NULL,             -- 신청자 이메일
    orderer_phone        VARCHAR(30) NOT NULL,              -- 신청자 연락처
    -- 기관 정보
    org_name             VARCHAR(200),                      -- 기관명
    org_type             VARCHAR(100),                      -- 기관 유형 (학원/대학/개인 등)
    -- 배송 정보
    delivery_postal_code VARCHAR(20),                       -- 우편번호
    delivery_address     TEXT NOT NULL,                     -- 배송 주소
    delivery_detail      VARCHAR(200),                      -- 상세 주소
    -- 결제 정보
    payment_method       textbook_payment_method_enum NOT NULL DEFAULT 'bank_transfer',
    depositor_name       VARCHAR(100),                      -- 입금자명 (신청자와 다를 경우)
    -- 세금계산서
    tax_invoice          BOOLEAN NOT NULL DEFAULT false,    -- 세금계산서 발행 여부
    tax_biz_number       VARCHAR(20),                       -- 사업자등록번호
    tax_email            VARCHAR(255),                      -- 세금계산서 수신 이메일
    -- 금액
    total_quantity       INT NOT NULL,                      -- 총 수량
    total_amount         INT NOT NULL,                      -- 총액 (KRW)
    currency             VARCHAR(3) NOT NULL DEFAULT 'KRW', -- 통화
    -- 비고
    notes                TEXT,                              -- 비고/요청사항
    -- 상태 변경 시각
    confirmed_at         TIMESTAMPTZ,                       -- 관리자 확인 시각
    paid_at              TIMESTAMPTZ,                       -- 입금 확인 시각
    shipped_at           TIMESTAMPTZ,                       -- 발송 시각
    delivered_at         TIMESTAMPTZ,                       -- 배송 완료 시각
    canceled_at          TIMESTAMPTZ,                       -- 취소 시각
    -- 기본 시각
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 3. textbook_item : 교재 주문 항목 (textbook : textbook_item = 1:N)
-- =============================================================================
CREATE TABLE textbook_item (
    item_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT NOT NULL REFERENCES textbook(order_id) ON DELETE CASCADE,
    textbook_language textbook_language_enum NOT NULL,      -- 교재 언어
    textbook_type     textbook_type_enum NOT NULL,          -- 학생용/교사용
    quantity          INT NOT NULL CHECK (quantity >= 1),   -- 수량
    unit_price        INT NOT NULL DEFAULT 25000,           -- 단가 (KRW)
    subtotal          INT NOT NULL,                         -- 소계 (quantity × unit_price)
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 4. admin_textbook_log : 관리자 교재 주문 작업 기록
-- =============================================================================
CREATE TABLE admin_textbook_log (
    log_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL REFERENCES users(user_id),
    order_id      BIGINT NOT NULL REFERENCES textbook(order_id) ON DELETE CASCADE,
    action        admin_action_enum NOT NULL,               -- 활동 종류
    before_data   JSONB,                                    -- 변경 전 데이터
    after_data    JSONB,                                    -- 변경 후 데이터
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 5. Indexes
-- =============================================================================

-- textbook
CREATE INDEX idx_textbook_status ON textbook(status);
CREATE INDEX idx_textbook_code ON textbook(order_code);
CREATE INDEX idx_textbook_created ON textbook(created_at DESC);

-- textbook_item
CREATE INDEX idx_textbook_item_order ON textbook_item(order_id);

-- admin_textbook_log
CREATE INDEX idx_admin_textbook_log_order ON admin_textbook_log(order_id);
