CREATE TYPE "admin_action_enum" AS ENUM (
  'create',
  'update',
  'banned',
  'reorder',
  'publish',
  'unpublish'
);

CREATE TYPE "user_auth_enum" AS ENUM (
  'HYMN',
  'admin',
  'manager',
  'learner'
);

CREATE TYPE "user_language_enum" AS ENUM (
  'ko',
  'en'
);

CREATE TYPE "user_gender_enum" AS ENUM (
  'none',
  'male',
  'female',
  'other'
);

CREATE TYPE "user_action_log_enum" AS ENUM (
  'signup',
  'find_id',
  'reset_pw',
  'update'
);

CREATE TYPE "user_set_language_enum" AS ENUM (
  'ko',
  'en'
);

CREATE TYPE "login_device_enum" AS ENUM (
  'mobile',
  'tablet',
  'desktop',
  'other'
);

CREATE TYPE "login_method_enum" AS ENUM (
  'email',
  'google',
  'apple'
);

CREATE TYPE "login_state_enum" AS ENUM (
  'active',
  'revoked',
  'expired',
  'logged_out',
  'compromised'
);

CREATE TYPE "login_event_enum" AS ENUM (
  'login',
  'logout',
  'refresh',
  'rotate',
  'fail',
  'reuse_detected'
);

CREATE TYPE "video_state_enum" AS ENUM (
  'ready',
  'open',
  'close'
);

CREATE TYPE "video_access_enum" AS ENUM (
  'public',
  'paid',
  'private',
  'promote'
);

CREATE TYPE "study_state_enum" AS ENUM (
  'ready',
  'open',
  'close'
);

CREATE TYPE "study_program_enum" AS ENUM (
  'basic_pronunciation',
  'basic_word',
  'basic_900',
  'topik_read',
  'topik_listen',
  'topik_write',
  'tbc'
);

CREATE TYPE "study_task_kind_enum" AS ENUM (
  'choice',
  'typing',
  'voice'
);

CREATE TYPE "study_task_log_action_enum" AS ENUM (
  'view',
  'start',
  'answer',
  'finish',
  'explain',
  'status'
);

CREATE TYPE "lesson_item_kind_enum" AS ENUM (
  'video',
  'task'
);

CREATE TABLE "admin_action_log" (
  "log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" BIGINT NOT NULL,
  "action_type" VARCHAR(50) NOT NULL,
  "target_table" VARCHAR(50),
  "target_id" BIGINT,
  "details" JSONB,
  "ip_address" INET,
  "user_agent" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_auth" user_auth_enum NOT NULL DEFAULT 'learner',
  "user_state" boolean NOT NULL DEFAULT true,
  "user_email" varchar(255) UNIQUE NOT NULL,
  "user_password" text NOT NULL,
  "user_name" varchar(100) NOT NULL,
  "user_nickname" varchar(100) NOT NULL,
  "user_language" user_language_enum NOT NULL DEFAULT 'ko',
  "user_country" varchar(50) NOT NULL,
  "user_birthday" date NOT NULL,
  "user_gender" user_gender_enum NOT NULL DEFAULT 'none',
  "user_check_email" boolean NOT NULL DEFAULT false,
  "user_terms_service" boolean NOT NULL DEFAULT false,
  "user_terms_personal" boolean NOT NULL DEFAULT false,
  "user_created_at" timestamptz NOT NULL DEFAULT (now()),
  "user_quit_at" timestamptz
);

CREATE TABLE "users_log" (
  "user_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "updated_by_user_id" bigint,
  "user_action_log" user_action_log_enum NOT NULL,
  "user_action_success" boolean NOT NULL DEFAULT true,
  "user_id" bigint NOT NULL,
  "user_auth_log" user_auth_enum,
  "user_state_log" boolean,
  "user_email_log" varchar(255),
  "user_certify_log" timestamptz,
  "user_password_log" boolean DEFAULT false,
  "user_nickname_log" varchar(100),
  "user_language_log" user_language_enum,
  "user_country_log" varchar(50),
  "user_birthday_log" date,
  "user_gender_log" user_gender_enum,
  "user_terms_service_log" boolean,
  "user_terms_personal_log" boolean,
  "user_log_created_at" timestamptz,
  "user_log_quit_at" timestamptz,
  "user_log_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "users_setting" (
  "user_id" bigint PRIMARY KEY,
  "user_set_language" user_set_language_enum NOT NULL DEFAULT 'ko',
  "user_set_timezone" varchar(64),
  "user_set_note_email" boolean NOT NULL DEFAULT false,
  "user_set_note_push" boolean NOT NULL DEFAULT false,
  "user_set_created_at" timestamptz NOT NULL DEFAULT (now()),
  "user_set_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "admin_users_log" (
  "admin_user_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL,
  "admin_pick_user_id" bigint NOT NULL,
  "admin_user_action" admin_action_enum NOT NULL,
  "admin_user_before" jsonb,
  "admin_user_after" jsonb,
  "admin_user_created_at" timestamptz NOT NULL DEFAULT (now()),
  "admin_user_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "user_export_data" (
  "user_data_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "user_data_status" boolean NOT NULL DEFAULT true,
  "user_data_course" jsonb,
  "user_data_lesson" jsonb,
  "user_data_expires_at" timestamptz,
  "user_data_created_at" timestamptz,
  "user_data_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "login" (
  "login_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "login_country" char(2) NOT NULL,
  "login_asn" bigint NOT NULL,
  "login_org" varchar(200) NOT NULL,
  "login_ip" inet NOT NULL,
  "login_os" varchar(100),
  "login_browser" varchar(100),
  "login_device" login_device_enum NOT NULL DEFAULT 'other',
  "login_method" login_method_enum NOT NULL DEFAULT 'email',
  "login_session_id" uuid NOT NULL,
  "login_refresh_hash" varchar(128),
  "login_user_agent" text,
  "login_begin_at" timestamptz NOT NULL DEFAULT (now()),
  "login_active_at" timestamptz,
  "login_expire_at" timestamptz,
  "login_state" login_state_enum NOT NULL DEFAULT 'active',
  "login_revoked_reason" text,
  "login_created_at" timestamptz NOT NULL DEFAULT (now()),
  "login_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "login_log" (
  "login_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "login_event_log" login_event_enum,
  "login_success_log" boolean,
  "login_access_log" char(64),
  "login_country_log" char(2),
  "login_asn_log" bigint,
  "login_org_log" varchar(200),
  "login_ip_log" inet,
  "login_os_log" varchar(100),
  "login_browser_log" varchar(100),
  "login_device_log" login_device_enum,
  "login_method_log" login_method_enum,
  "login_session_id_log" uuid,
  "login_refresh_hash_log" varchar(128),
  "login_user_agent_log" text,
  "login_begin_at_log" timestamptz NOT NULL DEFAULT (now()),
  "login_expire_at_log" timestamptz,
  "login_token_id_log" varchar,
  "login_fail_reason_log" text,
  "login_created_at_log" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "redis_session" (
  "redis_key" varchar(128) PRIMARY KEY,
  "session_id" uuid UNIQUE NOT NULL,
  "user_id" bigint NOT NULL,
  "login_id" bigint NOT NULL,
  "state" login_state_enum NOT NULL DEFAULT 'active',
  "issued_at" timestamptz NOT NULL DEFAULT (now()),
  "expire_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "ip" inet,
  "user_agent" text,
  "device" login_device_enum,
  "method" login_method_enum,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "redis_refresh" (
  "redis_key" varchar(160) PRIMARY KEY,
  "refresh_hash" varchar(128) UNIQUE NOT NULL,
  "session_id" uuid NOT NULL,
  "user_id" bigint,
  "issued_at" timestamptz NOT NULL DEFAULT (now()),
  "expire_at" timestamptz NOT NULL,
  "reused_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "redis_user_sessions" (
  "redis_key" varchar(128) PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "session_id" uuid NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT (now()),
  "expire_at" timestamptz NOT NULL
);

CREATE TABLE "video" (
  "video_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "updated_by_user_id" bigint NOT NULL,
  "video_idx" varchar(100) UNIQUE NOT NULL,
  "video_state" video_state_enum NOT NULL DEFAULT 'ready',
  "video_access" video_access_enum NOT NULL DEFAULT 'public',
  "video_url_vimeo" text NOT NULL,
  "video_created_at" timestamptz NOT NULL DEFAULT (now()),
  "video_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "video_log" (
  "video_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video_id" int NOT NULL,
  "user_id" bigint NOT NULL,
  "video_progress_log" int,
  "video_completed_log" boolean NOT NULL DEFAULT false,
  "video_watch_count_log" int NOT NULL DEFAULT 0,
  "video_first_watched_at_log" timestamptz,
  "video_last_watched_at_log" timestamptz,
  "video_last_ip_log" inet,
  "video_last_device_log" login_device_enum,
  "video_last_user_agent_log" jsonb,
  CONSTRAINT "uk_video_log_user_video" UNIQUE ("user_id", "video_id")
);

CREATE TABLE "video_tag" (
  "video_tag_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video_tag_key" varchar(30) UNIQUE NOT NULL,
  "video_tag_title" varchar(50) NOT NULL,
  "video_tag_subtitle" varchar(100),
  "video_tag_created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "video_tag_map" (
  "video_id" int NOT NULL,
  "video_tag_id" int NOT NULL
);

CREATE TABLE "video_stat_daily" (
  "video_stat_date" date,
  "video_id" int NOT NULL,
  "video_stat_views" int NOT NULL DEFAULT 0,
  "video_stat_completes" int NOT NULL DEFAULT 0
);

CREATE TABLE "admin_video_log" (
  "admin_video_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL,
  "admin_pick_video_id" int,
  "admin_pick_video_tag_id" int,
  "admin_video_action" admin_action_enum NOT NULL,
  "admin_video_before" jsonb,
  "admin_video_after" jsonb,
  "admin_video_created_at" timestamptz NOT NULL DEFAULT (now()),
  "admin_video_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "study" (
  "study_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "updated_by_user_id" bigint NOT NULL,
  "study_idx" varchar(100) UNIQUE NOT NULL,
  "study_state" study_state_enum NOT NULL DEFAULT 'ready',
  "study_program" study_program_enum NOT NULL DEFAULT 'tbc',
  "study_title" varchar(80),
  "study_subtitle" varchar(120),
  "study_description" text,
  "study_created_at" timestamptz NOT NULL DEFAULT (now()),
  "study_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "study_task" (
  "study_task_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "study_id" int NOT NULL,
  "updated_by_user_id" bigint NOT NULL,
  "study_task_kind" study_task_kind_enum NOT NULL,
  "study_task_seq" int NOT NULL DEFAULT 1,
  "study_task_created_at" timestamptz NOT NULL DEFAULT (now()),
  "study_task_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "study_task_choice" (
  "study_task_id" int PRIMARY KEY,
  "study_task_choice_question" text NOT NULL,
  "study_task_choice_1" text NOT NULL,
  "study_task_choice_2" text NOT NULL,
  "study_task_choice_3" text NOT NULL,
  "study_task_choice_4" text NOT NULL,
  "study_task_choice_answer" int NOT NULL,
  "study_task_choice_audio_url" text,
  "study_task_choice_image_url" text
);

CREATE TABLE "study_task_typing" (
  "study_task_id" int PRIMARY KEY,
  "study_task_typing_question" text,
  "study_task_typing_answer" text,
  "study_task_typing_image_url" text
);

CREATE TABLE "study_task_voice" (
  "study_task_id" int PRIMARY KEY,
  "study_task_voice_question" text,
  "study_task_voice_answer" text,
  "study_task_voice_audio_url" text,
  "study_task_voice_image_url" text
);

CREATE TABLE "study_task_explain" (
  "study_task_id" int NOT NULL,
  "explain_lang" user_set_language_enum NOT NULL DEFAULT 'ko',
  "explain_title" varchar(120),
  "explain_text" text,
  "explain_media_url" text,
  "explain_created_at" timestamptz NOT NULL DEFAULT (now()),
  "explain_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "study_task_status" (
  "study_task_id"                 INT NOT NULL, 
  "user_id"                       BIGINT NOT NULL REFERENCES "users"("user_id") ON DELETE CASCADE,
  "study_task_status_try_count"   INT NOT NULL DEFAULT 0,       
  "study_task_status_is_solved"   BOOLEAN NOT NULL DEFAULT false, 
  "study_task_status_last_attempt_at" TIMESTAMPTZ DEFAULT (now()),

  CONSTRAINT "fk_study_task_status_task" FOREIGN KEY ("study_task_id") REFERENCES "study_task"("study_task_id") ON DELETE CASCADE
);

CREATE TABLE "study_task_log" (
  "study_task_log_id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "study_task_id"               INT NOT NULL,
  "user_id"                     BIGINT NOT NULL REFERENCES "users"("user_id") ON DELETE CASCADE,
  "login_id"                    BIGINT NOT NULL,
  "study_task_action_log"       study_task_log_action_enum NOT NULL, 
  "study_task_try_no_log"       INT NOT NULL DEFAULT 1, 
  "study_task_is_correct_log"   BOOLEAN,
  "study_task_answer_log"       JSONB, 
  "study_task_created_at_log"   TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "study_task_ip_log"           INET,
  "study_task_device_log"       login_device_enum,
  "study_task_user_agent_log"   JSONB,

  CONSTRAINT "fk_study_task_log_task" FOREIGN KEY ("study_task_id") REFERENCES "study_task"("study_task_id") ON DELETE CASCADE
);

CREATE TABLE "admin_study_log" (
  "admin_study_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL,
  "admin_pick_study_id" int NOT NULL,
  "admin_pick_task_id" int,
  "admin_study_action" admin_action_enum NOT NULL,
  "admin_study_before" jsonb,
  "admin_study_after" jsonb,
  "admin_study_created_at" timestamptz NOT NULL DEFAULT (now()),
  "admin_study_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lesson" (
  "lesson_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "updated_by_user_id" bigint NOT NULL,
  "lesson_idx" varchar(100) UNIQUE NOT NULL,
  "lesson_title" varchar(120) NOT NULL,
  "lesson_subtitle" varchar(200),
  "lesson_description" text,
  "lesson_created_at" timestamptz NOT NULL DEFAULT (now()),
  "lesson_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lesson_item" (
  "lesson_id" int NOT NULL,
  "lesson_item_seq" int NOT NULL DEFAULT 1,
  "lesson_item_kind" lesson_item_kind_enum NOT NULL DEFAULT 'video',
  "video_id" int,
  "study_task_id" int
);

CREATE TABLE "lesson_progress" (
  "lesson_id" int NOT NULL,
  "user_id" bigint NOT NULL,
  "lesson_progress_percent" int NOT NULL DEFAULT 0,
  "lesson_progress_last_item_seq" int,
  "lesson_progress_last_progress_at" timestamptz
);

CREATE TABLE "admin_lesson_log" (
  "admin_lesson_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL,
  "admin_pick_lesson_id" int NOT NULL,
  "admin_pick_item_seq" int,
  "admin_pick_video_id" int,
  "admin_pick_task_id" int,
  "admin_lesson_action" admin_action_enum NOT NULL,
  "admin_lesson_before" jsonb,
  "admin_lesson_after" jsonb,
  "admin_lesson_created_at" timestamptz NOT NULL DEFAULT (now()),
  "admin_lesson_updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "pay" (
  "pay_id" int PRIMARY KEY,
  "user_id" int,
  "course_id" int,
  "pay_token" text,
  "pay_state" enum(ready,done,cancel) DEFAULT 'ready',
  "pay_start_at" timestamptz,
  "pay_end_at" timestamptz
);

CREATE TABLE "course" (
  "course_id" int PRIMARY KEY,
  "course_type" enum(video,study,live,package),
  "course_state" eunm(active,inactive,deleted) DEFAULT 'active',
  "course_title" varchar(255),
  "course_subtitle" text,
  "course_price" int,
  "course_created_at" timestamptz,
  "course_updated_at" timestamptz,
  "course_banned_at" timestamptz
);

CREATE TABLE "course_video" (
  "course_id" int,
  "video_id" int
);

CREATE TABLE "course_live" (
  "course_id" int,
  "live_id" int
);

CREATE TABLE "live" (
  "live_id" int PRIMARY KEY,
  "updated_by_user_id" int,
  "live_idx" varchar UNIQUE,
  "live_state" enum(ready,open,close) DEFAULT 'ready',
  "live_title" varchar(50),
  "live_subtitle" text,
  "live_start_at" timestamptz,
  "live_end_at" timestamptz
);

CREATE TABLE "live_zoom" (
  "live_zoom_id" int PRIMARY KEY,
  "live_id" int,
  "live_zoom_state" enum(pending,registered,failed) DEFAULT 'pending',
  "live_zoom_host_id" varchar(50),
  "live_zoom_passcode" varchar,
  "live_zoom_host_link" text,
  "live_zoom_guest_link" text,
  "live_zoom_start_at" timestamptz,
  "live_zoom_end_at" timestamptz
);

CREATE TABLE "live_log" (
  "live_log_id" int PRIMARY KEY,
  "live_id" int,
  "user_id" int,
  "live_log_join_time" timestamptz,
  "live_log_leave_time" timestamptz,
  "live_log_duration_min" int,
  "live_log_ip" text,
  "live_log_device" varchar(100),
  "live_log_network_type" varchar(100)
);

CREATE INDEX "index_admin_user_id" ON "admin_users_log" ("admin_user_id");

CREATE INDEX "index_target_user_id" ON "admin_users_log" ("admin_pick_user_id");

CREATE INDEX "index_export_data_user_id" ON "user_export_data" ("user_id");

CREATE UNIQUE INDEX "unique_login_session_id" ON "login" ("login_session_id");

CREATE UNIQUE INDEX "unique_refresh_hash" ON "login" ("login_refresh_hash");

CREATE INDEX "index_login_user_id" ON "login" ("user_id");

CREATE INDEX "index_login_state" ON "login" ("login_state");

CREATE INDEX "index_login_begin_at" ON "login" ("login_begin_at");

CREATE INDEX "index_login_expire_at" ON "login" ("login_expire_at");

CREATE INDEX "index_login_active_by_user" ON "login" ("user_id", "login_state");

CREATE INDEX "index_login_user_id_login_begin_at_log" ON "login_log" ("user_id", "login_begin_at_log");

CREATE INDEX "index_login_event_log" ON "login_log" ("login_event_log");

CREATE INDEX "index_redis_refresh_session_id" ON "redis_refresh" ("session_id");

CREATE INDEX "index_redis_refresh_user_id" ON "redis_refresh" ("user_id");

CREATE INDEX "index_redis_user_sessions_user_id" ON "redis_user_sessions" ("user_id");

CREATE UNIQUE INDEX "unique_redis_user_sessions_session_id" ON "redis_user_sessions" ("session_id");

CREATE INDEX "index_video_state_video_access" ON "video" ("video_state", "video_access");

CREATE INDEX "index_video_created_at" ON "video" ("video_created_at");

CREATE UNIQUE INDEX "unique_video_id_user_id" ON "video_log" ("video_id", "user_id");

CREATE INDEX "index_user_id_video_last_watched_at_log" ON "video_log" ("user_id", "video_last_watched_at_log");

CREATE INDEX "index_video_id_video_last_watched_at_log" ON "video_log" ("video_id", "video_last_watched_at_log");

CREATE UNIQUE INDEX "unique_video_id_video_tag_id" ON "video_tag_map" ("video_id", "video_tag_id");

CREATE UNIQUE INDEX "unique_video_stat_date_video_id" ON "video_stat_daily" ("video_stat_date", "video_id");

CREATE INDEX "index_admin_user_id" ON "admin_video_log" ("admin_user_id");

CREATE INDEX "index_admin_pick_video_id" ON "admin_video_log" ("admin_pick_video_id");

CREATE UNIQUE INDEX "unique_study_id_study_task_seq" ON "study_task" ("study_id", "study_task_seq");

CREATE INDEX "index_study_task_kind" ON "study_task" ("study_task_kind");

CREATE UNIQUE INDEX "unique_study_task_explain_lang" ON "study_task_explain" ("study_task_id", "explain_lang");

CREATE INDEX "index_explain_lang" ON "study_task_explain" ("explain_lang");

CREATE UNIQUE INDEX "unique_study_task_id_user_id" ON "study_task_status" ("study_task_id", "user_id");

CREATE INDEX "index_user_id_study_task_status_last_answer" ON "study_task_status" ("user_id", "study_task_status_last_attempt_at");

CREATE INDEX "index_tasklog_user_task_time" ON "study_task_log" ("user_id", "study_task_id", "study_task_created_at_log");

CREATE INDEX "index_tasklog_task_attempt" ON "study_task_log" ("study_task_id", "study_task_try_no_log");

CREATE INDEX "index_tasklog_login_time" ON "study_task_log" ("login_id", "study_task_created_at_log");

CREATE INDEX "idx_study_task_log_user_task" ON "study_task_log" ("user_id", "study_task_id");

CREATE INDEX "index_admin_study_actor" ON "admin_study_log" ("admin_user_id");

CREATE INDEX "index_admin_study_target" ON "admin_study_log" ("admin_pick_study_id");

CREATE INDEX "index_admin_study_task_target" ON "admin_study_log" ("admin_pick_task_id");

CREATE UNIQUE INDEX "unique_lesson_id_lesson_item_seq" ON "lesson_item" ("lesson_id", "lesson_item_seq");

CREATE INDEX "index_video_id" ON "lesson_item" ("video_id");

CREATE INDEX "index_study_task_id" ON "lesson_item" ("study_task_id");

CREATE UNIQUE INDEX "unique_lesson_id_user_id" ON "lesson_progress" ("lesson_id", "user_id");

CREATE INDEX "index_user_id" ON "lesson_progress" ("user_id");

CREATE INDEX "index_admin_lesson_actor" ON "admin_lesson_log" ("admin_user_id");

CREATE INDEX "index_admin_lesson_target" ON "admin_lesson_log" ("admin_pick_lesson_id");

CREATE INDEX "index_admin_lesson_item_seq" ON "admin_lesson_log" ("admin_pick_item_seq");

CREATE INDEX "index_admin_lesson_video_target" ON "admin_lesson_log" ("admin_pick_video_id");

CREATE INDEX "index_admin_lesson_task_target" ON "admin_lesson_log" ("admin_pick_task_id");

COMMENT ON COLUMN "users"."user_password" IS '암호화된 해시 저장';

COMMENT ON COLUMN "users_setting"."user_id" IS '1:1 with USERS';

COMMENT ON TABLE "admin_users_log" IS 'admin_user_created_at, admin_user_updated_at는 트리거로 자동 갱신';

COMMENT ON TABLE "login" IS 'CHECK (login_expire_at IS NULL OR login_expire_at >= login_begin_at)
CHECK (login_active_at IS NULL OR login_active_at >= login_begin_at)
CHECK (login_country = upper(login_country))';

COMMENT ON COLUMN "login"."login_session_id" IS 'Redis ak:session:<sid> 의 <sid>';

COMMENT ON COLUMN "login"."login_refresh_hash" IS 'Redis ak:refresh:<hash> 의 <hash> — UNIQUE 권장(Null 허용)';

COMMENT ON TABLE "login_log" IS 'CHECK (login_country_log = upper(login_country_log))';

COMMENT ON TABLE "redis_session" IS 'TTL은 expire_at 기준. 세션 본문은 직렬화(JSON 등)하되, 운영 상 조회 필드는 컬럼으로 문서화.';

COMMENT ON COLUMN "redis_session"."redis_key" IS '실제 Redis 키: ak:session:<sid>';

COMMENT ON COLUMN "redis_session"."session_id" IS '<sid> (LOGIN.login_session_id와 동일)';

COMMENT ON TABLE "redis_refresh" IS '로테이션(rotate-on-use) 시 refresh_hash 교체. 재사용 탐지 시 세션 일괄 폐기 정책과 연동.';

COMMENT ON COLUMN "redis_refresh"."redis_key" IS '실제 Redis 키: ak:refresh:<hash>';

COMMENT ON COLUMN "redis_refresh"."refresh_hash" IS '<hash> (DB LOGIN.login_refresh_hash와 동일 포맷)';

COMMENT ON COLUMN "redis_refresh"."session_id" IS '값: <sid>';

COMMENT ON COLUMN "redis_refresh"."reused_at" IS '재사용 탐지 시 타임스탬프(옵션)';

COMMENT ON TABLE "redis_user_sessions" IS '실제 Redis에서는 set/list로 보관. dbdiagram 문서화를 위해 행 형태로 표현.';

COMMENT ON COLUMN "redis_user_sessions"."redis_key" IS '실제 Redis 키: ak:user_sessions:<uid>';

COMMENT ON TABLE "video" IS 'video_updated_at는 트리거로 자동 갱신 권장';

COMMENT ON TABLE "video_log" IS 'CHECK: video_progress_log BETWEEN 0 AND 100';

COMMENT ON TABLE "admin_video_log" IS 'admin_video_created_at, admin_video_updated_at는 트리거로 자동 갱신 권장';

COMMENT ON TABLE "study" IS 'updated_at는 트리거로 자동 갱신 권장';

COMMENT ON TABLE "study_task" IS '앱/트리거 규칙: basic900→typing|voice, topik_read→choice, topik_listen→choice, topik_write→typing';

COMMENT ON TABLE "study_task_choice" IS 'CHECK (study_task_choice_answer BETWEEN 1 AND 4)';

COMMENT ON TABLE "study_task_typing" IS 'CHECK (tolerance_rate BETWEEN 0 AND 100)';

COMMENT ON TABLE "study_task_voice" IS 'CHECK (score_threshold BETWEEN 0 AND 100)';

COMMENT ON TABLE "study_task_explain" IS 'updated_at는 트리거로 자동 갱신 권장';

COMMENT ON TABLE "study_task_status" IS 'CHECK (study_task_status_try >= 0) AND CHECK (study_task_status_best BETWEEN 0 AND 100)';

COMMENT ON TABLE "study_task_log" IS 'CHECK (study_task_try_no_log >= 1) AND CHECK (study_task_score_log BETWEEN 0 AND 100)';

COMMENT ON COLUMN "study_task_log"."study_task_answer_log" IS 'choice:{selected}; typing:{typed,wer}; voice:{asr,pron,audio}';

COMMENT ON TABLE "admin_study_log" IS 'created_at/updated_at는 트리거로 자동 갱신 권장';

COMMENT ON TABLE "lesson" IS 'lesson_updated_at는 트리거로 자동 갱신 권장';

COMMENT ON TABLE "lesson_item" IS '규칙: item_kind=video면 video_id NOT NULL, item_kind=task면 study_task_id NOT NULL (앱/트리거로 강제)';

COMMENT ON TABLE "lesson_progress" IS 'CHECK (lesson_progress_percent BETWEEN 0 AND 100)';

COMMENT ON TABLE "admin_lesson_log" IS 'created_at/updated_at는 트리거로 자동 갱신 권장';

ALTER TABLE "users_log" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "users_setting" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "admin_users_log" ADD FOREIGN KEY ("admin_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "admin_users_log" ADD FOREIGN KEY ("admin_pick_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_export_data" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "login" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "login_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE SET NULL;

ALTER TABLE "redis_session" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "redis_session" ADD FOREIGN KEY ("login_id") REFERENCES "login" ("login_id");

ALTER TABLE "redis_refresh" ADD FOREIGN KEY ("session_id") REFERENCES "login" ("login_session_id");

ALTER TABLE "redis_refresh" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "redis_user_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "redis_user_sessions" ADD FOREIGN KEY ("session_id") REFERENCES "login" ("login_session_id");

ALTER TABLE "redis_session" ADD FOREIGN KEY ("session_id") REFERENCES "login" ("login_session_id");

ALTER TABLE "video" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "video_log" ADD FOREIGN KEY ("video_id") REFERENCES "video" ("video_id");

ALTER TABLE "video_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

/* 로그인 아이디 사용안함 : ALTER TABLE "video_log" ADD FOREIGN KEY ("login_id") REFERENCES "login" ("login_id");*/

ALTER TABLE "video_tag_map" ADD FOREIGN KEY ("video_id") REFERENCES "video" ("video_id");

ALTER TABLE "video_tag_map" ADD FOREIGN KEY ("video_tag_id") REFERENCES "video_tag" ("video_tag_id");

ALTER TABLE "video_stat_daily" ADD FOREIGN KEY ("video_id") REFERENCES "video" ("video_id");

ALTER TABLE "admin_video_log" ADD FOREIGN KEY ("admin_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "admin_video_log" ADD FOREIGN KEY ("admin_pick_video_id") REFERENCES "video" ("video_id");

ALTER TABLE "admin_video_log" ADD FOREIGN KEY ("admin_pick_video_tag_id") REFERENCES "video_tag" ("video_tag_id");

ALTER TABLE "study" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "study_task" ADD FOREIGN KEY ("study_id") REFERENCES "study" ("study_id");

ALTER TABLE "study_task" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "study_task_choice" ADD FOREIGN KEY ("study_task_id") REFERENCES "study_task" ("study_task_id");

ALTER TABLE "study_task_typing" ADD FOREIGN KEY ("study_task_id") REFERENCES "study_task" ("study_task_id");

ALTER TABLE "study_task_voice" ADD FOREIGN KEY ("study_task_id") REFERENCES "study_task" ("study_task_id");

ALTER TABLE "study_task_explain" ADD FOREIGN KEY ("study_task_id") REFERENCES "study_task" ("study_task_id");

ALTER TABLE "study_task_status" ADD FOREIGN KEY ("study_task_id") REFERENCES "study_task" ("study_task_id");

ALTER TABLE "study_task_status" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "study_task_log" ADD FOREIGN KEY ("study_task_id") REFERENCES "study_task" ("study_task_id");

ALTER TABLE "study_task_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "study_task_log" ADD FOREIGN KEY ("login_id") REFERENCES "login" ("login_id");

ALTER TABLE "admin_study_log" ADD FOREIGN KEY ("admin_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "admin_study_log" ADD FOREIGN KEY ("admin_pick_study_id") REFERENCES "study" ("study_id");

ALTER TABLE "admin_study_log" ADD FOREIGN KEY ("admin_pick_task_id") REFERENCES "study_task" ("study_task_id");

ALTER TABLE "lesson" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "lesson_item" ADD FOREIGN KEY ("lesson_id") REFERENCES "lesson" ("lesson_id");

ALTER TABLE "lesson_item" ADD FOREIGN KEY ("video_id") REFERENCES "video" ("video_id");

ALTER TABLE "lesson_item" ADD FOREIGN KEY ("study_task_id") REFERENCES "study_task" ("study_task_id");

ALTER TABLE "lesson_progress" ADD FOREIGN KEY ("lesson_id") REFERENCES "lesson" ("lesson_id");

ALTER TABLE "lesson_progress" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "admin_lesson_log" ADD FOREIGN KEY ("admin_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "admin_lesson_log" ADD FOREIGN KEY ("admin_pick_lesson_id") REFERENCES "lesson" ("lesson_id");

ALTER TABLE "admin_lesson_log" ADD FOREIGN KEY ("admin_pick_video_id") REFERENCES "video" ("video_id");

ALTER TABLE "admin_lesson_log" ADD FOREIGN KEY ("admin_pick_task_id") REFERENCES "study_task" ("study_task_id");

/* 아래 부터는 테이블 생성 후 진행 */
ALTER TABLE "pay" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "pay" ADD FOREIGN KEY ("course_id") REFERENCES "course" ("course_id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course_id") REFERENCES "course" ("course_id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("video_id") REFERENCES "video" ("video_id");

ALTER TABLE "course_live" ADD FOREIGN KEY ("course_id") REFERENCES "course" ("course_id");

ALTER TABLE "course_live" ADD FOREIGN KEY ("live_id") REFERENCES "live" ("live_id");

ALTER TABLE "live" ADD FOREIGN KEY ("updated_by_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "live_zoom" ADD FOREIGN KEY ("live_id") REFERENCES "live" ("live_id");

ALTER TABLE "live_log" ADD FOREIGN KEY ("live_id") REFERENCES "live" ("live_id");

ALTER TABLE "live_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");